**Inclass: SQL Query**
- Part of Data Science in Python Specialization for PT Freeport Indonesia
- Course Length: 12 hours
- Last Updated: September 2025
___

- Developed by [Algoritma](https://algorit.ma)'s product division and instructors team

# Working with SQL Databases

## Database Schema

Database `chinook.db` terdiri dari 11 tabel yang berisi sampel data dari sebuah toko yang menjual media digital:

- Data terkait media seperti pada tabel `tracks`, `albums`, `artists`, `genres`, `media_types`, `playlists`, `playlist_track` merupakan data asli dari library Apple iTunes.
- Informasi mengenai `customers` dan `employees` dibuat menggunakan nama dan alamat fiktif yang dapat ditemukan di Google maps, dan data lain yang diformat dengan baik (telepon, fax, email, dll).
- Informasi penjualan `invoices` dan `invoice_items` dihasilkan secara otomatis menggunakan data acak untuk periode tahun 2009-2013.

Skema berikut sering disebut sebagai **Entity Relationship Diagram (ERD)**, menunjukkan:
1. Entitas (Tabel)
2. Atribut (Kolom beserta tipe datanya)
3. Kardinalitas (Hubungan antar tabel)

![](assets/chinookschema.png)

Gambar di atas adalah ERD untuk database chinook:

- **Satu database** terdiri dari **beberapa tabel**
- **Setiap tabel** terdiri dari beberapa **atribut/kolom**
- Terdapat kolom unik yang membedakan satu tabel dengan lainnya, disebut sebagai **Primary Key (PK)**. PK dapat digunakan sebagai kolom penghubung antar tabel saat dilakukan proses join (penggabungan) tabel.

## Database Connection

Sebelum kita dapat melakukan pembacaan data, kita perlu menghubungkan Python dengan database yang ingin kita akses. Tiap koneksi database memerlukan library yang berbeda, tergantung database tersebut kompatibel dengan DBMS apa.

<br>

<details>
    <summary>✨ Connecting to MySQL</summary>
    
```python
import pymysql
  
conn = pymysql.connect(
    host = HOST_NAME,
    port = PORT_NUMBER,
    user = USER_NAME,
    password = PASSWORD,
    db = DATABASE_NAME)
```
</details>

<br>

<details>
    <summary>✨ Connecting to Snowflake</summary>

🌐 Documentation : [Snowflake Python Connector](https://docs.snowflake.com/en/developer-guide/python-connector/python-connector)

```python
import snowflake.connector

conn = snowflake.connector.connect(
    user=USER,
    password=PASSWORD,
    account=ACCOUNT,
    warehouse=WAREHOUSE,
    database=DATABASE,
    schema=SCHEMA)
```
</details>

<br>

<details>
    <summary>✨ Connecting to PostgreSQL</summary>
    
```python
import psycopg2

conn = psycopg2.connect(
    host = HOST_NAME,
    port = PORT_NUMBER,
    user = USER_NAME,
    password = PASSWORD,
    database = DATABASE_NAME)
```
</details>

<br>

<details>
    <summary>✨ Connecting to Microsoft SQL Server</summary>
    
```python
import pyodbc 
conn = pyodbc.connect(
    'Driver={ODBC Driver 17 for SQL Server};'
    'Server=host;'
    'PORT=1433;'
    'UID=user;'
    'PWD=password;'
    'Database=database;')
```
</details>

Pada materi kali ini, kita akan menggunakan database **chinook.db**, database lokal yang kompatibel dengan **SQLite**, sehingga kita akan menggunakan library `sqlite3`. Library `sqlite3` merupakan library bawaan dari Python.

In [81]:
import sqlite3 
import pandas as pd

Untuk menghubungkan database **SQLite** menggunakan library `sqlite3`, kita perlu menggunakan method `connect()`


<details>

<summary>Connection to PostgreSQL Example</summary>

```python
import psycopg2

conn_postgre = psycopg2.connect(
    host = 'localhost',
    port = 5432,
    user = 'postgres',
    password = '12qwaszx',
    database = 'BankDatabase')
```

</details>

In [82]:
# import psycopg2

# conn_postgre = psycopg2.connect(
#     host = 'localhost',
#     port = 5432,
#     user = 'postgres',
#     password = '12qwaszx',
#     database = 'BankDatabase')

In [83]:
# membuat object conn untuk connection
conn = sqlite3.connect('data_input/chinook.db')

Kemudian untuk membaca data, kita menggunakan `pd.read_sql_query()` dan menyertakan parameter berikut:

- `sql`: SQL query dalam bentuk string
- `con`: SQL connection

Silahkan kunjungi [official documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql_query.html) untuk detail lebih lanjut.

Parameter `sql` dapat diisi dengan beberapa _statement_ (perintah), seperti:

## `SELECT` Statements

`SELECT` digunakan untuk memilih **kolom** dari sebuah **tabel**.

Syntax `SELECT`:

```sql
SELECT <NAMA_KOLOM>
FROM <NAMA_TABLE>
```

❓ Misal, hanya ingin mengambil kolom `AlbumId` dan `Title` dari tabel `albums`

In [84]:
# your code here
query = 'SELECT AlbumId, Title FROM albums'

Kemudian, kita dapat menampilkan data tersebut dalam bentuk dataframe melalui `pd.read_sql_query()`

In [85]:
# your code here
pd.read_sql_query(query, conn)

     AlbumId                                              Title
0          1              For Those About To Rock We Salute You
1          2                                  Balls to the Wall
2          3                                  Restless and Wild
3          4                                  Let There Be Rock
4          5                                           Big Ones
..       ...                                                ...
342      343                             Respighi:Pines of Rome
343      344  Schubert: The Late String Quartets & String Qu...
344      345                                Monteverdi: L'Orfeo
345      346                              Mozart: Chamber Music
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...

[347 rows x 2 columns]

In [86]:
# query = 'SELECT * FROM transaction'

# pd.read_sql_query(query, conn_postgre)

❓ Bagaimana jika kita ingin mengambil **semua kolom** dari tabel `albums`? Gunakan command `SELECT *`

In [87]:
# your code here
query = 'SELECT * FROM albums'

pd.read_sql_query(query, conn)

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

💡 **Note**:<br> Berbeda dari Python, perintah yang ada di SQL bersifat **case insensitive**. Query di atas dapat juga dituliskan sebagai `select * from albums`. Namun, demi kemudahan pembacaan, statement biasa dituliskan dengan huruf besar (dalam hal ini `SELECT` dan `FROM`).

In [88]:
# your code here
query = 'sElEcT * fROm aLbUms'

pd.read_sql_query(query, conn)

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

### `LIMIT` Statement

Statement `LIMIT` digunakan untuk mengambil beberapa baris pertama pada data.

❓ Ambil **5 baris pertama** dan seluruh kolom dari tabel `artists`

In [89]:
# your code here
query = 'SELECT * FROM artists LIMIT 5'

pd.read_sql_query(query, conn)

   ArtistId               Name
0         1              AC/DC
1         2             Accept
2         3          Aerosmith
3         4  Alanis Morissette
4         5    Alice In Chains

Statement `LIMIT` sama seperti method `head()` di pandas dataframe

In [90]:
query = 'SELECT * FROM artists'

artists = pd.read_sql_query(query, conn)
artists.head()

   ArtistId               Name
0         1              AC/DC
1         2             Accept
2         3          Aerosmith
3         4  Alanis Morissette
4         5    Alice In Chains

## `JOIN` Statement

Statement `JOIN` digunakan untuk **menggabungkan dua tabel** menjadi satu tabel melalui **kolom penghubung** yang sama. Operasi `JOIN` dapat dilakukan lebih dari satu kali dalam satu SQL query. Berikut adalah diagram ilustrasi beberapa macam operasi SQL `JOIN`:

![](assets/sqljoins.png)

💡 `JOIN` yang sering digunakan:
- `LEFT JOIN` paling sering digunakan pada sebagian besar skenario bisnis. `LEFT JOIN` mengembalikan semua baris pada tabel kiri **terlepas** dari apakah ada baris yang cocok pada tabel kanan.
- `INNER JOIN` adalah tipe join yang sangat intuitif dan mudah dipahami. Query ini mengembalikan semua baris di tabel kiri yang cocok dengan tabel kanan.

**Note**:

- `RIGHT JOIN` hampir tidak pernah digunakan karena ekuivalen dengan `LEFT JOIN` hanya mengganti peletakkan tabel kiri dan kanannya saja.
- `FULL JOIN` sangat jarang digunakan. Selain alasan komputasi, tipe join ini mengembalikan semua baris dari kedua tabel terlepas dari apakah ada kecocokan atau tidak, sehingga menghasilkan DataFrame dengan banyak missing value.

Ilustrasi terkait ke-empat tipe join dapat dilihat pada [Visual JOIN](https://joins.spathon.com/).

Syntax `JOIN`:

```sql
SELECT <COLUMNS>
FROM <LEFT_TABLE>

[LEFT|INNER|FULL] JOIN <RIGHT_TABLE>
ON <LEFT_TABLE>.key = <RIGHT_TABLE>.key
```

Perhatikan kembali skema database `chinook.db`:

1. Tabel `albums`: 
    - `AlbumId`
    - `Title`
    - `ArtistId`

 2. Tabel `artists`:
    - `ArtistId`
    - `Name` 
    
❓**Kasus:** Kita ingin mendapatkan DataFrame yang menampilkan semua judul album (`Title`) dari tabel `albums` secara lengkap, ditambahkan dengan informasi beserta kolom `Name`. Perhatikan bahwa kolom `Name` terdapat pada tabel `artists`, sedangkan kolom `AlbumId` dan `Title` terdapat pada tabel `albums`.

- `LEFT JOIN`
- Tabel kiri: albums
- Tabel kanan: artists
- Penghubung: ArtistId

📝 **Note**: Ketika menuliskan nama-nama kolom pada query yang menggunakan 2 tabel atau lebih harus menambahkan nama tabelnya sebelum menuliskan naam kolomnya dengan format: `table.column`

In [91]:
# your code here
query = 'SELECT albums.Title, artists.Name FROM albums LEFT JOIN artists ON albums.ArtistId = artists.ArtistId'

pd.read_sql_query(query, conn)

,Title,Name
0,For Those About To Rock We Salute You,AC/DC
1,Balls to the Wall,Accept
2,Restless and Wild,Accept
3,Let There Be Rock,AC/DC
4,Big Ones,Aerosmith
...,...,...
342,Respighi:Pines of Rome,Eugene Ormandy
343,Schubert: The Late String Quartets & String Qu...,Emerson String Quartet
344,Monteverdi: L'Orfeo,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
345,Mozart: Chamber Music,Nash Ensemble
346,Koyaanisqatsi (Soundtrack from the Motion Pict...,Philip Glass Ensemble

📌 **Tips:**

String pada python yang kita gunakan (`'query'`) hanya dapat menyimpan teks/query dalam satu line code. Jika kita gunakan untuk menuliskan query yang panjang maka akan cukup sulit untuk pemahamannya. 

Sebagai alternatif, anda dapat mengapit SQL query dengan `'''query'''` (petik tiga kali) agar dapat menuliskan multiline query:

In [92]:
# code here
query = '''
    SELECT albums.Title, artists.Name 
    FROM albums 
    LEFT JOIN artists 
    ON albums.ArtistId = artists.ArtistId
'''
pd.read_sql_query(query, conn)

,Title,Name
0,For Those About To Rock We Salute You,AC/DC
1,Balls to the Wall,Accept
2,Restless and Wild,Accept
3,Let There Be Rock,AC/DC
4,Big Ones,Aerosmith
...,...,...
342,Respighi:Pines of Rome,Eugene Ormandy
343,Schubert: The Late String Quartets & String Qu...,Emerson String Quartet
344,Monteverdi: L'Orfeo,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
345,Mozart: Chamber Music,Nash Ensemble
346,Koyaanisqatsi (Soundtrack from the Motion Pict...,Philip Glass Ensemble

Terkadang penamaan kolom ataupun tabel pada database cukup panjang dan redundan untuk diketik, ataupun belum cukup informatif.

📌 **Tips:** <br>
Penggunaan statement `AS` dapat digunakan untuk melakukan **aliasing / rename** nama tabel maupun nama kolom.

In [93]:
# code here
query = '''
    SELECT al.Title AS AlbumTitle, ar.Name AS ArtistName
    FROM albums AS al
    LEFT JOIN artists AS ar
    ON al.ArtistId = ar.ArtistId
'''
pd.read_sql_query(query, conn)

,AlbumTitle,ArtistName
0,For Those About To Rock We Salute You,AC/DC
1,Balls to the Wall,Accept
2,Restless and Wild,Accept
3,Let There Be Rock,AC/DC
4,Big Ones,Aerosmith
...,...,...
342,Respighi:Pines of Rome,Eugene Ormandy
343,Schubert: The Late String Quartets & String Qu...,Emerson String Quartet
344,Monteverdi: L'Orfeo,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
345,Mozart: Chamber Music,Nash Ensemble
346,Koyaanisqatsi (Soundtrack from the Motion Pict...,Philip Glass Ensemble

⚠️ **Hati-hati!**<br>
Saat melakukan `LEFT JOIN`, peletakkan tabel kiri dan kanan sangat berpengaruh terhadap hasil penggabungan.

❓Sebagai perbanding, sekarang coba kita tukar tabel `artists` menjadi tabel kiri, sedangkan `albums` menjadi tabel kanan.

Object `df` di bawah menampilkan semua data `artists` walaupun artist tersebut tidak ada di tabel `albums`.

In [94]:
# FROM artists LEFT JOIN albums
query = '''
    SELECT albums.Title AS AlbumTitle, artists.Name AS ArtistName
    FROM artists
    LEFT JOIN albums
    ON albums.artistId = artists.artistId
'''

df = pd.read_sql_query(query, conn)
df

,AlbumTitle,ArtistName
0,For Those About To Rock We Salute You,AC/DC
1,Let There Be Rock,AC/DC
2,Balls to the Wall,Accept
3,Restless and Wild,Accept
4,Big Ones,Aerosmith
...,...,...
413,"Locatelli: Concertos for Violin, Strings and C...","Mela Tenenbaum, Pro Musica Prague & Richard Kapp"
414,Schubert: The Late String Quartets & String Qu...,Emerson String Quartet
415,Monteverdi: L'Orfeo,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
416,Mozart: Chamber Music,Nash Ensemble
417,Koyaanisqatsi (Soundtrack from the Motion Pict...,Philip Glass Ensemble

In [95]:
# cek baris dengan missing value
df[df.isna().any(axis=1)]

    AlbumTitle                                         ArtistName
50        None                         Milton Nascimento & Bebeto
51        None                                            Azymuth
55        None                                      João Gilberto
56        None                                     Bebel Gilberto
57        None                                      Jorge Vercilo
..         ...                                                ...
327       None                 DJ Dolores & Orchestra Santa Massa
328       None                                          Seu Jorge
329       None                               Sabotage E Instituto
330       None                                    Stereo Maracana
377       None  Academy of St. Martin in the Fields, Sir Nevil...

[71 rows x 2 columns]

❗**Latihan**

Dengan perintah `JOIN`, lakukan penggabungan untuk menampilkan keseluruhan informasi pada table `invoice_items` dan juga kolom `InvoiceDate` yang berasal dari table `invoices`.

In [96]:
# code here
query = '''
    SELECT invoice_items.*, invoices.InvoiceDate 
    FROM invoice_items

    LEFT JOIN invoices 
    ON invoices.InvoiceId = invoice_items.InvoiceId
'''

pd.read_sql_query(query, conn)

,InvoiceLineId,InvoiceId,TrackId,UnitPrice,Quantity,InvoiceDate
0,1,1,2,0.99,1,2009-01-01 00:00:00
1,2,1,4,0.99,1,2009-01-01 00:00:00
2,3,2,6,0.99,1,2009-01-02 00:00:00
3,4,2,8,0.99,1,2009-01-02 00:00:00
4,5,2,10,0.99,1,2009-01-02 00:00:00
...,...,...,...,...,...,...
2235,2236,411,3136,0.99,1,2013-12-14 00:00:00
2236,2237,411,3145,0.99,1,2013-12-14 00:00:00
2237,2238,411,3154,0.99,1,2013-12-14 00:00:00
2238,2239,411,3163,0.99,1,2013-12-14 00:00:00
2239,2240,412,3177,1.99,1,2013-12-22 00:00:00

### 🤿 Dive Deeper: SQL JOINS

Buat query untuk menampilkan informasi:

- Semua baris dan kolom pada tabel `tracks`
- Kolom `Name` pada tabel `artists`

In [97]:
# your code here
query = '''
    SELECT tracks.*, artists.Name AS ArtistName
    FROM tracks

    LEFT JOIN albums ON albums.AlbumId = tracks.AlbumId

    LEFT JOIN artists ON albums.ArtistId = artists.ArtistId
'''

pd.read_sql_query(query, conn)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice,ArtistName
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99,AC/DC
1,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99,Accept
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99,Accept
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99,Accept
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99,Accept
...,...,...,...,...,...,...,...,...,...,...
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,2,24,None,286741,4718950,0.99,Eugene Ormandy
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,Franz Schubert,139200,2283131,0.99,Emerson String Quartet
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,2,24,Claudio Monteverdi,66639,1189062,0.99,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99,Nash Ensemble
3502,3503,Koyaanisqatsi,347,2,10,Philip Glass,206005,3305164,0.99,Philip Glass Ensemble

## `GROUP BY` Statement

Di `pandas`, kita bisa menggunakan metode `.crosstab()` untuk membuat tabel agregasi. Sedangkan di SQL, kita menggunakan kombinasi statement `GROUP BY` dan menggunakan beberapa fungsi agregasi pada statement `SELECT`:

Berikut beberapa fungsi agregasi yang tersedia pada SQL:

```sql
- COUNT()
- SUM()
- AVG()
- MIN()
- MAX()
```

❓ Pada tabel `invoices`, misalkan kita ingin mengetahui jumlah besar transaksi (`Total`) dan berapa transaksi yang dilakukan untuk setiap `CustomerId`:

In [98]:
# your code here
query = '''
    SELECT CustomerId, SUM(Total) AS TotalSales, COUNT(CustomerId) AS Frequency
    FROM invoices

    GROUP BY CustomerId
'''

pd.read_sql_query(query, conn).head()

   CustomerId  TotalSales  Frequency
0           1       39.62          7
1           2       37.62          7
2           3       39.62          7
3           4       39.62          7
4           5       40.62          7

💡 Kemudian, jika misalkan kita ingin mengetahui CustomerId top 5 yang memiliki transaksi terbesar, maka kita dapat gunakan `ORDER BY` dan menentukan apakah kita ingin mengurutkannya dengan:

- `ASC`: mengurutkan dari kecil ke besar
- `DESC`: mengurutkan dari besar ke kecil

In [99]:
# your code here
query = '''
    SELECT CustomerId, SUM(Total) AS TotalSales, COUNT(CustomerId) AS Frequency
    FROM invoices

    GROUP BY CustomerId
    ORDER BY TotalSales DESC
'''

pd.read_sql_query(query, conn)

    CustomerId  TotalSales  Frequency
0            6       49.62          7
1           26       47.62          7
2           57       46.62          7
3           45       45.62          7
4           46       45.62          7
5           24       43.62          7
6           28       43.62          7
7           37       43.62          7
8            7       42.62          7
9           25       42.62          7
10          44       41.62          7
11           5       40.62          7
12          43       40.62          7
13          48       40.62          7
14           1       39.62          7
15           3       39.62          7
16           4       39.62          7
17          17       39.62          7
18          20       39.62          7
19          22       39.62          7
20          34       39.62          7
21          42       39.62          7
22          15       38.62          7
23          19       38.62          7
24          39       38.62          7
25          40       38.62          7
26          51       38.62          7
27          58       38.62          7
28           2       37.62          7
29           8       37.62          7
30           9       37.62          7
31          10       37.62          7
32          11       37.62          7
33          12       37.62          7
34          13       37.62          7
35          14       37.62          7
36          16       37.62          7
37          18       37.62          7
38          21       37.62          7
39          23       37.62          7
40          27       37.62          7
41          29       37.62          7
42          30       37.62          7
43          31       37.62          7
44          32       37.62          7
45          33       37.62          7
46          35       37.62          7
47          36       37.62          7
48          38       37.62          7
49          41       37.62          7
50          47       37.62          7
51          49       37.62          7
52          50       37.62          7
53          52       37.62          7
54          53       37.62          7
55          54       37.62          7
56          55       37.62          7
57          56       37.62          7
58          59       36.64          6

### 🤿 Dive Deeper: SQL Data Aggregation

Seorang produser musik ingin menciptakan lagu dengan mempertimbangkan genre yang akan laku di market. Sebelum mulai, ia terlebih dahulu melakukan riset tentang genre musik apa yang sedang hits saat ini. Sebagai seorang data analyst, Anda diminta untuk membantu produser musik dalam membuat keputusan yang tepat.

**Pertanyaan:** Tampilkan top 5 genre musik dengan jumlah lagu terjual paling banyak, sertakan juga dengan jumlah quantity dan rata-rata harga track untuk masing-masing genre!


<br>

<details>
    <summary><i>👉 Klik di sini untuk hint</i></summary>
    
Berikut adalah code yang dapat Anda gunakan untuk mengetahui `genres` paling populer dari semua _item_ (lagu) yant terjual.

```python
query = '''
    SELECT ___
    FROM ___

    LEFT JOIN ___ ON ___
    LEFT JOIN ___ ON ___

    GROUP BY ___
    ORDER BY ___
'''
```
</details>

In [100]:
# your code here
query = '''
    SELECT genres.Name, COUNT(invoice_items.InvoiceLineId) AS FrequencySong, AVG(invoice_items.UnitPrice) AS AveragePrice
    FROM genres

    LEFT JOIN tracks ON tracks.GenreId = genres.GenreId
    LEFT JOIN invoice_items ON invoice_items.Trackid = tracks.Trackid

    GROUP BY genres.Name
    ORDER BY FrequencySong DESC
'''

pd.read_sql_query(query, conn)

                  Name  FrequencySong  AveragePrice
0                 Rock            835          0.99
1                Latin            386          0.99
2                Metal            264          0.99
3   Alternative & Punk            244          0.99
4                 Jazz             80          0.99
5                Blues             61          0.99
6             TV Shows             47          1.99
7             R&B/Soul             41          0.99
8            Classical             41          0.99
9               Reggae             30          0.99
10               Drama             29          1.99
11                 Pop             28          0.99
12          Soundtrack             20          0.99
13    Sci Fi & Fantasy             20          1.99
14         Hip Hop/Rap             17          0.99
15          Bossa Nova             15          0.99
16         Alternative             14          0.99
17               World             13          0.99
18         Heavy Metal             12          0.99
19   Electronica/Dance             12          0.99
20      Easy Listening             10          0.99
21              Comedy              9          1.99
22     Science Fiction              6          1.99
23       Rock And Roll              6          0.99
24               Opera              0           NaN

## `WHERE` Statement

Sekarang, kita akan melihat teknik untuk melakukan **conditional subsetting** atau **filter baris** menggunakan statement `WHERE` yang diikuti dengan **kondisi**.

### Comparison Operator

Statement `WHERE` dapat dikombinasikan dengan comparison operator seperti: 

- Mathematical Operator : `=`, `!=`, `>`, `>=`, `<`, dan `<=`
- Logical Operator : `AND`, `OR`, dan `NOT`:

Sebagai contoh, misalkan kita ingin melakukan analisis terhadap semua data `invoices` yang ada di `BillingCountry` Germany, maka kita bisa menambahkan statement `WHERE` sebagai berikut:

In [101]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE BillingCountry = 'Germany'
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,6,37,2009-01-19 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,0.99
2,7,38,2009-02-01 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
3,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
4,29,36,2009-05-05 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98
5,30,38,2009-05-06 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,3.96
6,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
7,52,38,2009-08-08 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,5.94
8,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91
9,95,36,2010-02-13 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,8.91
10,104,38,2010-03-29 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,0.99
11,127,37,2010-07-13 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,1.98
12,138,37,2010-08-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,13.86
13,193,37,2011-04-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,14.91
14,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
15,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96
16,224,36,2011-09-20 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98
17,225,38,2011-09-20 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
18,236,38,2011-10-31 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,13.86
19,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94
20,247,36,2011-12-23 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,3.96
21,269,36,2012-03-26 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,5.94
22,291,38,2012-06-30 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,8.91
23,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99
24,321,36,2012-11-14 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,0.99
25,322,37,2012-11-27 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,1.98
26,345,37,2013-03-01 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,3.96
27,367,37,2013-06-03 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,5.94

❗**Latihan**

Misalkan kita hanya tertarik untuk menganalisis data yang terjadi di `Canada` dan `USA`. Kira-kira bagaimana cara mengimplementasikannya dalam bentuk query SQL?

In [102]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE BillingCountry = 'Canada' OR BillingCountry = 'USA'
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
1,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
2,13,16,2009-02-19 00:00:00,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,0.99
3,14,17,2009-03-04 00:00:00,1 Microsoft Way,Redmond,WA,USA,98052-8300,1.98
4,15,19,2009-03-04 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,1.98
...,...,...,...,...,...,...,...,...,...
142,405,20,2013-11-21 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,0.99
143,406,21,2013-12-04 00:00:00,801 W 4th Street,Reno,NV,USA,89503,1.98
144,407,23,2013-12-04 00:00:00,69 Salem Street,Boston,MA,USA,2113,1.98
145,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96
146,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94

### `IN` Operator

Operator `IN` memungkinkan kita menentukan beberapa nilai untuk perbandingan. Misalnya, seperti pada kasus sebelumnya, kita ingin mengambil semua data `invoices` yang terjadi di negara (`BillingCountry`) Canada dan juga USA:

In [103]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE BillingCountry IN ('Canada', 'USA')
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
1,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
2,13,16,2009-02-19 00:00:00,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,0.99
3,14,17,2009-03-04 00:00:00,1 Microsoft Way,Redmond,WA,USA,98052-8300,1.98
4,15,19,2009-03-04 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,1.98
...,...,...,...,...,...,...,...,...,...
142,405,20,2013-11-21 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,0.99
143,406,21,2013-12-04 00:00:00,801 W 4th Street,Reno,NV,USA,89503,1.98
144,407,23,2013-12-04 00:00:00,69 Salem Street,Boston,MA,USA,2113,1.98
145,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96
146,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94

### Operating Dates

Pada operasi kondisi pada statement `WHERE` sebelumnya, kita dapat mengambil semua data `invoices` pada negara Germany. Namun, juga umum untuk kita melakukan conditional query untuk mengambil data pada **rentang tanggal** tertentu.

❓ Sebelum lanjut, mari kita ambil seluruh data dari tabel `invoices` dan cek tipe datanya:

In [104]:
query = '''
    SELECT *
    FROM invoices
'''

df_invoice = pd.read_sql_query(query, conn)
df_invoice

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
...,...,...,...,...,...,...,...,...,...
407,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96
408,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
409,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91
410,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86
411,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,None,India,110017,1.99

Perhatikan bahwa `InvoiceDate` dikenali sebagai tipe data `object`. `pd.read_sql_query()` berperilaku seperti `pd.read_csv()`, yaitu secara default membaca tipe data suatu kolom sebagai numerik dan objek.

Meskipun begitu, selama `InvoiceDate` sudah diatur sebagai data `datetime`, maka kita dapat melakukan proses operasi tanggal pada query kolom tersebut.

❓**Kasus**: Kita ingin meninjau penjualan (`invoices`) di seluruh negara pada tahun 2012 saja.

In [105]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE InvoiceDate >= '2012-01-01' AND InvoiceDate < '2013-01-01'
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,250,55,2012-01-01 00:00:00,421 Bourke Street,Sidney,NSW,Australia,2010,13.86
1,251,10,2012-01-09 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,0.99
2,252,11,2012-01-22 00:00:00,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,1.98
3,253,13,2012-01-22 00:00:00,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,1.98
4,254,15,2012-01-23 00:00:00,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,3.96
...,...,...,...,...,...,...,...,...,...
78,328,15,2012-12-15 00:00:00,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,0.99
79,329,16,2012-12-28 00:00:00,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,1.98
80,330,18,2012-12-28 00:00:00,627 Broadway,New York,NY,USA,10012-2612,1.98
81,331,20,2012-12-29 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,3.96
82,332,24,2012-12-30 00:00:00,162 E Superior Street,Chicago,IL,USA,60611,5.94

**[Optional]** Datetime Extraction Using `STRFTIME()`:

Fungsi `STRFTIME()` memungkinkan kita untuk mengekstrak komponen tanggal/waktu menggunakan sebuah format, berikut input dari `STRFTIME()`:

```python
STRFTIME(format, column)
```

- `format` : strftime format codes (🌐Reference: https://strftime.org/)
- `column` : datetime column

In [106]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE STRFTIME('%Y', InvoiceDate) == '2012'
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,250,55,2012-01-01 00:00:00,421 Bourke Street,Sidney,NSW,Australia,2010,13.86
1,251,10,2012-01-09 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,0.99
2,252,11,2012-01-22 00:00:00,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,1.98
3,253,13,2012-01-22 00:00:00,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,1.98
4,254,15,2012-01-23 00:00:00,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,3.96
...,...,...,...,...,...,...,...,...,...
78,328,15,2012-12-15 00:00:00,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,0.99
79,329,16,2012-12-28 00:00:00,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,1.98
80,330,18,2012-12-28 00:00:00,627 Broadway,New York,NY,USA,10012-2612,1.98
81,331,20,2012-12-29 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,3.96
82,332,24,2012-12-30 00:00:00,162 E Superior Street,Chicago,IL,USA,60611,5.94

In [107]:
# STRFTIME untuk membuat kolom baru (bulan invoice)
query = '''
    SELECT *, STRFTIME('%m', InvoiceDate) AS InvoiceMonth
    FROM invoices
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,InvoiceMonth
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,01
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96,01
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94,01
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91,01
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86,01
...,...,...,...,...,...,...,...,...,...,...
407,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96,12
408,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94,12
409,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91,12
410,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86,12
411,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,None,India,110017,1.99,12

### `BETWEEN` Operator

Melanjutkan kasus sebelumnya, apabila kita ingin menggunakan kondisi pada rentang tertentu, pendekatan yang umum digunakan adalah operator `BETWEEN`. Berikut adalah syntax umum dari `WHERE`:

```sql
WHERE column BETWEEN value1 AND value2
```

In [108]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE InvoiceDate BETWEEN '2012-01-01' AND '2012-12-31'
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,250,55,2012-01-01 00:00:00,421 Bourke Street,Sidney,NSW,Australia,2010,13.86
1,251,10,2012-01-09 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,0.99
2,252,11,2012-01-22 00:00:00,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,1.98
3,253,13,2012-01-22 00:00:00,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,1.98
4,254,15,2012-01-23 00:00:00,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,3.96
...,...,...,...,...,...,...,...,...,...
78,328,15,2012-12-15 00:00:00,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,0.99
79,329,16,2012-12-28 00:00:00,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,1.98
80,330,18,2012-12-28 00:00:00,627 Broadway,New York,NY,USA,10012-2612,1.98
81,331,20,2012-12-29 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,3.96
82,332,24,2012-12-30 00:00:00,162 E Superior Street,Chicago,IL,USA,60611,5.94

In [109]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE STRFTIME('%Y', InvoiceDate) BETWEEN '2012' AND '2013'
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,250,55,2012-01-01 00:00:00,421 Bourke Street,Sidney,NSW,Australia,2010,13.86
1,251,10,2012-01-09 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,0.99
2,252,11,2012-01-22 00:00:00,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,1.98
3,253,13,2012-01-22 00:00:00,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,1.98
4,254,15,2012-01-23 00:00:00,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,3.96
...,...,...,...,...,...,...,...,...,...
158,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96
159,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
160,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91
161,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86
162,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,None,India,110017,1.99

In [110]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE CustomerId BETWEEN 50 AND 59
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,41,50,2009-06-23 00:00:00,C/ San Bernardo 85,Madrid,None,Spain,28015,0.99
1,162,50,2010-12-15 00:00:00,C/ San Bernardo 85,Madrid,None,Spain,28015,1.98
2,173,50,2011-01-25 00:00:00,C/ San Bernardo 85,Madrid,None,Spain,28015,13.86
3,228,50,2011-09-25 00:00:00,C/ San Bernardo 85,Madrid,None,Spain,28015,8.91
4,357,50,2013-05-01 00:00:00,C/ San Bernardo 85,Madrid,None,Spain,28015,1.98
...,...,...,...,...,...,...,...,...,...
64,45,59,2009-07-08 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,5.94
65,97,59,2010-02-26 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,1.99
66,218,59,2011-08-20 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,1.98
67,229,59,2011-09-30 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,13.86
68,284,59,2012-05-30 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,8.91

### `LIKE` Operator

Operator `LIKE` sangat berguna jika kita perlu mencocokan bagian tertentu dari sebuah string daripada menggunakan operator sama dengan (`=`).

Sebagai contoh, kita ingin mendapatkan informasi customer yang tinggal pada daerah yang `BillingPostalCode` **dimulai** dengan angka 107. 

Kita dapat menggunakan `%` yang disebut sebagai [wildcard character](https://www.w3schools.com/sql/sql_wildcards.asp)

In [111]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE BillingPostalCode LIKE '107%'
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,7,38,2009-02-01 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
1,29,36,2009-05-05 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98
2,30,38,2009-05-06 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,3.96
3,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
4,52,38,2009-08-08 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,5.94
5,95,36,2010-02-13 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,8.91
6,104,38,2010-03-29 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,0.99
7,224,36,2011-09-20 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98
8,225,38,2011-09-20 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
9,236,38,2011-10-31 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,13.86
10,247,36,2011-12-23 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,3.96
11,269,36,2012-03-26 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,5.94
12,291,38,2012-06-30 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,8.91
13,321,36,2012-11-14 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,0.99

❓Bagaimana jika anda menggunakan wildcard `%` diawal string?

In [112]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE BillingPostalCode LIKE '%01'
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,23,59,2009-04-05 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,3.96
1,45,59,2009-07-08 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,5.94
2,91,22,2010-02-08 00:00:00,120 S Orange Ave,Orlando,FL,USA,32801,1.98
3,97,59,2010-02-26 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,1.99
4,114,22,2010-05-13 00:00:00,120 S Orange Ave,Orlando,FL,USA,32801,3.96
5,136,22,2010-08-15 00:00:00,120 S Orange Ave,Orlando,FL,USA,32801,5.94
6,188,22,2011-04-05 00:00:00,120 S Orange Ave,Orlando,FL,USA,32801,0.99
7,218,59,2011-08-20 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,1.98
8,229,59,2011-09-30 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,13.86
9,284,59,2012-05-30 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,8.91
10,309,22,2012-09-26 00:00:00,120 S Orange Ave,Orlando,FL,USA,32801,3.98
11,320,22,2012-11-06 00:00:00,120 S Orange Ave,Orlando,FL,USA,32801,13.86
12,375,22,2013-07-07 00:00:00,120 S Orange Ave,Orlando,FL,USA,32801,8.91

**Diskusi:**

- Jika `BillingPostalCode LIKE '107%'`, maka semua baris dengan kode pos **dimulai** angka 107 akan tampil.
- Jika `BillingPostalCode LIKE '%107'`, maka semua baris dengan kode pos **diakhiri** angka 107 akan tampil.

❓ Menurut Anda apa yang akan muncul jika kita menggunakan `%` **sebelum dan sesudah** pencocokan pola?

In [113]:
# your code here
query = '''
    SELECT *
    FROM invoices

    WHERE BillingPostalCode LIKE '%107%'
'''

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,7,38,2009-02-01 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
1,29,36,2009-05-05 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98
2,30,38,2009-05-06 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,3.96
3,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
4,52,38,2009-08-08 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,5.94
5,85,45,2010-01-08 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,1.98
6,95,36,2010-02-13 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,8.91
7,96,45,2010-02-18 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,21.86
8,104,38,2010-03-29 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,0.99
9,151,45,2010-10-19 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,8.91
10,224,36,2011-09-20 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98
11,225,38,2011-09-20 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
12,236,38,2011-10-31 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,13.86
13,247,36,2011-12-23 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,3.96
14,269,36,2012-03-26 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,5.94
15,280,45,2012-05-25 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,1.98
16,291,38,2012-06-30 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,8.91
17,303,45,2012-08-27 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,3.96
18,321,36,2012-11-14 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,0.99
19,325,45,2012-11-29 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,5.94
20,377,45,2013-07-20 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,0.99

### 🤿 Dive Deeper: SQL Conditional Subsetting

Pada 5 data pertama `customerinv`, kita bisa melihat kolom `Company` mungkin tidak dapat diandalkan karena bernilai `None`. Tetapi jika Anda memperhatikan kolom `Email`, Anda dapat melihat beberapa customer memiliki domain email `apple`, yang bisa menjadi indikator perusahaan mereka.

In [114]:
query = """
    SELECT FirstName, LastName, Email, Company, InvoiceId, InvoiceDate, BillingCountry, Total
    FROM invoices
    LEFT JOIN customers
    ON invoices.CustomerId = customers.CustomerId
"""

customerinv = pd.read_sql_query(query, conn)
customerinv.head()

,FirstName,LastName,Email,Company,InvoiceId,InvoiceDate,BillingCountry,Total
0,Leonie,Köhler,leonekohler@surfeu.de,None,1,2009-01-01 00:00:00,Germany,1.98
1,Bjørn,Hansen,bjorn.hansen@yahoo.no,None,2,2009-01-02 00:00:00,Norway,3.96
2,Daan,Peeters,daan_peeters@apple.be,None,3,2009-01-03 00:00:00,Belgium,5.94
3,Mark,Philips,mphilips12@shaw.ca,Telus,4,2009-01-06 00:00:00,Canada,8.91
4,John,Gordon,johngordon22@yahoo.com,None,5,2009-01-11 00:00:00,USA,13.86

**Pertanyaan:** Bagaimana jika kita ingin menghitung jumlah pelanggan yang bekerja di Apple Inc. dengan menggunakan domain `Email` sebagai pengganti indikator `Company`?

Silahkan lengkapi query diatas kemudian jawab pertanyaan berikut:

Berapa jumlah pelanggan yang bekerja di Apple?

- [ ] 412
- [ ] 49
- [x] 7
- [ ] 14

In [115]:
# your code here
query = """
    SELECT FirstName, LastName, Email, Company, InvoiceId, InvoiceDate, BillingCountry, Total
    FROM invoices
    LEFT JOIN customers
    ON invoices.CustomerId = customers.CustomerId

    WHERE Email LIKE '%@apple%'
"""

apple_customers = pd.read_sql_query(query, conn)
apple_customers.shape

(49, 8)

In [116]:
apple_customers.drop_duplicates(subset='Email')

,FirstName,LastName,Email,Company,InvoiceId,InvoiceDate,BillingCountry,Total
0,Daan,Peeters,daan_peeters@apple.be,None,3,2009-01-03 00:00:00,Belgium,5.94
1,Hugh,O'Reilly,hughoreilly@apple.ie,None,10,2009-02-03 00:00:00,Ireland,5.94
2,Tim,Goyer,tgoyer@apple.com,Apple Inc.,15,2009-03-04 00:00:00,USA,1.98
4,Terhi,Hämäläinen,terhi.hamalainen@apple.fi,None,53,2009-08-11 00:00:00,Finland,8.91
7,Astrid,Gruber,astrid.gruber@apple.at,None,78,2009-12-08 00:00:00,Austria,1.98
9,Isabelle,Mercier,isabelle_mercier@apple.fr,None,84,2010-01-08 00:00:00,France,1.98
10,Ladislav,Kovács,ladislav_kovacs@apple.hu,None,85,2010-01-08 00:00:00,Hungary,1.98

In [117]:
# your code here
query = """
    SELECT DISTINCT FirstName, LastName, Email
    FROM invoices
    LEFT JOIN customers
    ON invoices.CustomerId = customers.CustomerId

    WHERE Email LIKE '%@apple%'
"""

apple_customers = pd.read_sql_query(query, conn)
apple_customers

  FirstName    LastName                      Email
0    Astrid      Gruber     astrid.gruber@apple.at
1      Daan     Peeters      daan_peeters@apple.be
2       Tim       Goyer           tgoyer@apple.com
3  Isabelle     Mercier  isabelle_mercier@apple.fr
4     Terhi  Hämäläinen  terhi.hamalainen@apple.fi
5  Ladislav      Kovács   ladislav_kovacs@apple.hu
6      Hugh    O'Reilly       hughoreilly@apple.ie

### ✅ Knowledge Check: SQL Statement Structure

Susunlah 8 baris SQL statement berikut menjadi sebuah kerangka urutan syntax yang benar:

1. `GROUP BY <nama_kolom>`

2. `LIMIT <banyaknya_baris>`

3. `SELECT <nama_kolom> AS ...`

4. `[LEFT|INNER|FULL] JOIN <tabel_kanan> AS ...`

5. `ORDER BY <nama_kolom> [ASC|DESC]`

6. `FROM <nama_tabel> AS ...`

7. `WHERE <kondisi>`
    
8. `ON <tabel>.key = <tabel>.key`

> **JAWABAN**: Urutan yang benar adalah

3-6-4-8-7-1-5-2

In [118]:
# your code here
query = '''
    SELECT CustomerId, SUM(Total) AS TotalSales, COUNT(CustomerId) AS Frequency, BillingCountry
    FROM invoices

    WHERE BillingCountry = 'Germany'

    GROUP BY CustomerId

    
'''

pd.read_sql_query(query, conn)

   CustomerId  TotalSales  Frequency BillingCountry
0           2       37.62          7        Germany
1          36       37.62          7        Germany
2          37       43.62          7        Germany
3          38       37.62          7        Germany

## `HAVING` Statement

Kita telah mempelajari bagaimana melakukan agregasi di SQL dan penggunaan pernyataan `WHERE`. Namun, terdapat sebuah masalah ketika kita ingin menggunakan `WHERE` untuk memfilter baris berdasarkan kondisi pada kolom yang sudah diagregasi.  

Oleh karena itu kita perlu menggunakan statement lain yaitu `HAVING`. Perbedaan utama antara `HAVING` dan `WHERE` adalah bahwa klausa `HAVING` digunakan setelah fungsi agregasi. 

Perhatikan query dibawah ini di mana kita ingin mengambil data pelanggan dengan total jumlah invoice sepanjang waktu lebih besar dari 47:

In [119]:
# code here
query = """
    SELECT CustomerId, SUM(Total) as TotalValue
    FROM INVOICES

    GROUP BY CustomerId
    HAVING TotalValue > 47
"""

pd.read_sql_query(query, conn)

   CustomerId  TotalValue
0           6       49.62
1          26       47.62

---

# Advanced SQL Query Concepts

Setelah mempelajari perintah dasar SQL seperti `SELECT`, `JOIN`, `GROUP BY`, dan `WHERE`. Pada bagian ini, kita akan mempelajari bagaimana mengaplikasikan beberapa konsep query untuk menyelesaikan kebutuhan analisis data yang lebih kompleks. Konsep-konsep ini akan membantu kita menulis query yang lebih fleksibel, efisien, serta mampu menangani kasus penggunaan nyata yang sering ditemui dalam dunia kerja.

## SQL Subquery

Dalam beberapa kasus tertentu, kita ingin melakukan filter baris berdasarkan syarat tertentu dimana nilai-nilai kondisi hanya dapat dihitung menggunakan hasil dari query lainnya. Umumnya, subquery dapat didefinisikan dengan menuliskan query didalam query yang dibungkus dengan tanda kurung:

```sql
SELECT column1
FROM tables1
WHERE (
    SELECT column2
    FROM tables2
)
```

Pada section ini, kita akan membahas beberapa jenis subqueries yang dapat kita gunakan:

### Scalar Subquery

**Scalar subquery** mengembalikan satu nilai saja (satu baris dan satu kolom). Subquery jenis ini sering digunakan ketika hanya satu nilai yang diharapkan, misalnya dalam perhitungan dan perbandingan pada statement `WHERE`.

Sebagai contoh, kita ingin menampilkan informasi `CustomerId` dan `Total` dari tabel `invoices` yang memiliki `Total` diatas rata-rata:

In [120]:
# code here
query = """
    SELECT AVG(Total)
    FROM invoices
"""

pd.read_sql_query(query, conn)

   AVG(Total)
0    5.651942

In [121]:
# code here
query = """
    SELECT CustomerId, Total
    FROM invoices
    
    WHERE Total > (SELECT AVG(Total) FROM invoices)
"""

pd.read_sql_query(query, conn)

     CustomerId  Total
0             8   5.94
1            14   8.91
2            23  13.86
3            46   5.94
4            52   8.91
..          ...    ...
174          56   8.91
175           6  25.86
176          29   5.94
177          35   8.91
178          44  13.86

[179 rows x 2 columns]

### Single-Column Subquery

**Single-Column subquery** memberikan informasi dari satu kolom dan beberapa baris. Subquery jenis ini sering digunakan ketika hanya terdapat beberapa nilai dalam suatu kolom dibutuhkan, misalnya ketika menggunakan statement `IN` pada pada `WHERE`.

Sebagai contoh, kita ingin menampilkan informasi lagu-lagu (`Name`) dari tabel `tracks` yang dibeli oleh Top 5 `CustomerId` dengan `Total` dari tabel `invoices` terbesar.

Pertama-tama, kita akan mempersiapkan informasi untuk memperoleh informasi Top 5 Customer tersebut:

In [122]:
# code here
query = """
    SELECT CustomerId
    FROM invoices

    GROUP BY CustomerId
    ORDER BY SUM(Total) DESC

    LIMIT 5
"""

pd.read_sql_query(query, conn)

   CustomerId
0           6
1          26
2          57
3          45
4          46

Sebenarnya, Untuk menarik informasi yang dibutuhkan, kita bisa saja menuliskan list `CustomerId` dalam kondisi secara **hard-code** seperti ini:

In [123]:
query = """
    SELECT invoices.CustomerId, tracks.Name
    FROM invoices

    LEFT JOIN invoice_items ON invoice_items.InvoiceId = invoices.InvoiceId
    LEFT JOIN tracks ON tracks.TrackId = invoice_items.TrackId

    WHERE CustomerId IN (6, 26, 57, 45, 46)
"""

pd.read_sql_query(query, conn)

     CustomerId                                               Name
0             6                   When You Gonna Learn (Digeridoo)
1             6                  Whatever It Is, I Just Can't Stop
2             6                                Black Capricorn Day
3             6                            Were Do We Go From Here
4             6                                        Light Years
..          ...                                                ...
185          57                                          The Ocean
186          57                                            Hot Dog
187          57                                          Black Dog
188          57                                 Misty Mountain Hop
189          57  Scheherazade, Op. 35: I. The Sea and Sindbad's...

[190 rows x 2 columns]

Namun cara tersebut tidak disarankan. Jika ada penambahan value dalam database, sehingga bisa saja bukan lagi `CustomerId` 6, 26, 57, 45, 46 yang merupakan top 5 customers. Maka dari itu, kita perlu menggunakan **subquery** agar query kita lebih **dinamis terhadap perubahan data**.

Untuk itu mari kita persiapkan subquery yang hanya mengembalikan list Top 5 `CustomerId` berdasarkan `Total` pembelian:

In [124]:
# code here
query = """
    SELECT invoices.CustomerId, tracks.Name
    FROM invoices

    LEFT JOIN invoice_items ON invoice_items.InvoiceId = invoices.InvoiceId
    LEFT JOIN tracks ON tracks.TrackId = invoice_items.TrackId

    WHERE CustomerId IN (
        SELECT CustomerId
        FROM invoices

        GROUP BY CustomerId
        ORDER BY SUM(Total) DESC

        LIMIT 5
    )
"""

pd.read_sql_query(query, conn)

     CustomerId                                               Name
0             6                   When You Gonna Learn (Digeridoo)
1             6                  Whatever It Is, I Just Can't Stop
2             6                                Black Capricorn Day
3             6                            Were Do We Go From Here
4             6                                        Light Years
..          ...                                                ...
185          57                                          The Ocean
186          57                                            Hot Dog
187          57                                          Black Dog
188          57                                 Misty Mountain Hop
189          57  Scheherazade, Op. 35: I. The Sea and Sindbad's...

[190 rows x 2 columns]

Kedua tabel akan menghasilkan hasil yang sama, namun query yang digunakan akan lebih dinamis.

### Multi-Column Subquery

**Multi-Column subquery** memberikan informasi dari beberapa kolom sekaligus. Subquery jenis ini sering digunakan jika kita butuh mengambil beberapa kriteria dari beberapa kolom, misalnya ketika menggunakan statement `IN` pada pada `WHERE`.

Sebagai contoh, dari tabel `invoices`, kita ingin menampilkan informasi transaksi `InvoiceId`, `InvoiceDate` manakah yang memiliki `Total` terbesar untuk masing-masing `CustomerId`:

Pertama-tama, kita mencoba untuk mempersiapkan informasi untuk memperoleh nilai `Total` maksimum untuk tiap customer:

In [125]:
# code here
query = """
    SELECT CustomerId, MAX(Total)
    FROM invoices

    GROUP BY CustomerId
"""

pd.read_sql_query(query, conn)

    CustomerId  MAX(Total)
0            1       13.86
1            2       13.86
2            3       13.86
3            4       15.86
4            5       16.86
5            6       25.86
6            7       18.86
7            8       13.86
8            9       13.86
9           10       13.86
10          11       13.86
11          12       13.86
12          13       13.86
13          14       13.86
14          15       13.86
15          16       13.86
16          17       13.86
17          18       13.86
18          19       13.86
19          20       13.86
20          21       13.86
21          22       13.86
22          23       13.86
23          24       15.86
24          25       18.86
25          26       23.86
26          27       13.86
27          28       13.86
28          29       13.86
29          30       13.86
30          31       13.86
31          32       13.86
32          33       13.86
33          34       13.86
34          35       13.86
35          36       13.86
36          37       14.91
37          38       13.86
38          39       13.86
39          40       13.86
40          41       13.86
41          42       13.86
42          43       16.86
43          44       13.86
44          45       21.86
45          46       21.86
46          47       13.86
47          48       13.86
48          49       13.86
49          50       13.86
50          51       13.86
51          52       13.86
52          53       13.86
53          54       13.86
54          55       13.86
55          56       13.86
56          57       17.91
57          58       13.86
58          59       13.86

Kemudian, informasi diatas dapat dijadikan kriteria yang akan difilter dengan menggunakan `WHERE`:

In [126]:
# code here
query = """
    SELECT CustomerId, InvoiceId, InvoiceDate, Total
    FROM invoices

    WHERE (CustomerId, Total) IN (
        SELECT CustomerId, MAX(Total)
        FROM invoices

        GROUP BY CustomerId    
    )
"""

pd.read_sql_query(query, conn)

    CustomerId  InvoiceId          InvoiceDate  Total
0            1        327  2012-12-07 00:00:00  13.86
1            2         12  2009-02-11 00:00:00  13.86
2            3        110  2010-04-21 00:00:00  13.86
3            4        208  2011-06-29 00:00:00  15.86
4            5        306  2012-09-05 00:00:00  16.86
5            6        404  2013-11-13 00:00:00  25.86
6            7         89  2010-01-18 00:00:00  18.86
7            8        187  2011-03-28 00:00:00  13.86
8            9        285  2012-06-04 00:00:00  13.86
9           10        383  2013-08-12 00:00:00  13.86
10          11         68  2009-10-17 00:00:00  13.86
11          12        166  2010-12-25 00:00:00  13.86
12          13        264  2012-03-03 00:00:00  13.86
13          14        362  2013-05-11 00:00:00  13.86
14          15         47  2009-07-16 00:00:00  13.86
15          16        145  2010-09-23 00:00:00  13.86
16          17        243  2011-12-01 00:00:00  13.86
17          18        341  2013-02-07 00:00:00  13.86
18          19         26  2009-04-14 00:00:00  13.86
19          20        124  2010-06-22 00:00:00  13.86
20          21        222  2011-08-30 00:00:00  13.86
21          22        320  2012-11-06 00:00:00  13.86
22          23          5  2009-01-11 00:00:00  13.86
23          24        103  2010-03-21 00:00:00  15.86
24          25        201  2011-05-29 00:00:00  18.86
25          26        299  2012-08-05 00:00:00  23.86
26          27        397  2013-10-13 00:00:00  13.86
27          28         82  2009-12-18 00:00:00  13.86
28          29        180  2011-02-25 00:00:00  13.86
29          30        278  2012-05-04 00:00:00  13.86
30          31        376  2013-07-12 00:00:00  13.86
31          32         61  2009-09-16 00:00:00  13.86
32          33        159  2010-11-24 00:00:00  13.86
33          34        257  2012-02-01 00:00:00  13.86
34          35        355  2013-04-10 00:00:00  13.86
35          36         40  2009-06-15 00:00:00  13.86
36          37        193  2011-04-23 00:00:00  14.91
37          38        236  2011-10-31 00:00:00  13.86
38          39        334  2013-01-07 00:00:00  13.86
39          40         19  2009-03-14 00:00:00  13.86
40          41        117  2010-05-22 00:00:00  13.86
41          42        215  2011-07-30 00:00:00  13.86
42          43        313  2012-10-06 00:00:00  16.86
43          44        411  2013-12-14 00:00:00  13.86
44          45         96  2010-02-18 00:00:00  21.86
45          46        194  2011-04-28 00:00:00  21.86
46          47        292  2012-07-05 00:00:00  13.86
47          48        390  2013-09-12 00:00:00  13.86
48          49         75  2009-11-17 00:00:00  13.86
49          50        173  2011-01-25 00:00:00  13.86
50          51        271  2012-04-03 00:00:00  13.86
51          52        369  2013-06-11 00:00:00  13.86
52          53         54  2009-08-16 00:00:00  13.86
53          54        152  2010-10-24 00:00:00  13.86
54          55        250  2012-01-01 00:00:00  13.86
55          56        348  2013-03-10 00:00:00  13.86
56          57         88  2010-01-13 00:00:00  17.91
57          58        131  2010-07-23 00:00:00  13.86
58          59        229  2011-09-30 00:00:00  13.86

In [127]:
# SUB QUERY pada statement SELECT 
query = """
    SELECT *, (SELECT AVG(Total) FROM invoices)
    FROM invoices
"""

pd.read_sql_query(query, conn)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,(SELECT AVG(Total) FROM invoices)
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,5.651942
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96,5.651942
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94,5.651942
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91,5.651942
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86,5.651942
...,...,...,...,...,...,...,...,...,...,...
407,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96,5.651942
408,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94,5.651942
409,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91,5.651942
410,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86,5.651942
411,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,None,India,110017,1.99,5.651942

In [128]:
# SUB QUERY pada statement FROM 
query = """
    SELECT *
    FROM (        
        SELECT CustomerId
        FROM invoices

        GROUP BY CustomerId
        ORDER BY SUM(Total) DESC

        LIMIT 5
    ) AS top5customer

    LEFT JOIN invoices ON invoices.CustomerId = top5customer.CustomerId
    
"""

pd.read_sql_query(query, conn)

,CustomerId,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,6,46,6,2009-07-11 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,8.91
1,6,175,6,2011-02-15 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,1.98
2,6,198,6,2011-05-20 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,3.96
3,6,220,6,2011-08-22 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,5.94
4,6,272,6,2012-04-11 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,0.99
5,6,393,6,2013-10-03 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,1.98
6,6,404,6,2013-11-13 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,25.86
7,26,70,26,2009-11-07 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,1.98
8,26,93,26,2010-02-09 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,3.96
9,26,115,26,2010-05-14 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,5.94
10,26,167,26,2011-01-02 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,0.99
11,26,288,26,2012-06-25 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,1.98
12,26,299,26,2012-08-05 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,23.86
13,26,354,26,2013-04-05 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,8.91
14,57,22,57,2009-04-04 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,1.98
15,57,33,57,2009-05-15 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,13.86
16,57,88,57,2010-01-13 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,17.91
17,57,217,57,2011-08-20 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,1.98
18,57,240,57,2011-11-22 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,3.96
19,57,262,57,2012-02-24 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,5.94
20,57,314,57,2012-10-14 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,0.99
21,45,85,45,2010-01-08 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,1.98
22,45,96,45,2010-02-18 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,21.86
23,45,151,45,2010-10-19 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,8.91
24,45,280,45,2012-05-25 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,1.98
25,45,303,45,2012-08-27 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,3.96
26,45,325,45,2012-11-29 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,5.94
27,45,377,45,2013-07-20 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,0.99
28,46,10,46,2009-02-03 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,5.94
29,46,62,46,2009-09-24 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,0.99
30,46,183,46,2011-03-18 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,1.98
31,46,194,46,2011-04-28 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,21.86
32,46,249,46,2011-12-27 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,8.91
33,46,378,46,2013-08-02 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,1.98
34,46,401,46,2013-11-04 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,3.96

In [129]:
# CTE
query = """
    WITH top5customer AS (
        SELECT CustomerId
        FROM invoices

        GROUP BY CustomerId
        ORDER BY SUM(Total) DESC

        LIMIT 5
    )

    SELECT *
    FROM top5customer

    LEFT JOIN invoices ON invoices.CustomerId = top5customer.CustomerId
    
"""

pd.read_sql_query(query, conn)

,CustomerId,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,6,46,6,2009-07-11 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,8.91
1,6,175,6,2011-02-15 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,1.98
2,6,198,6,2011-05-20 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,3.96
3,6,220,6,2011-08-22 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,5.94
4,6,272,6,2012-04-11 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,0.99
5,6,393,6,2013-10-03 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,1.98
6,6,404,6,2013-11-13 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,25.86
7,26,70,26,2009-11-07 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,1.98
8,26,93,26,2010-02-09 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,3.96
9,26,115,26,2010-05-14 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,5.94
10,26,167,26,2011-01-02 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,0.99
11,26,288,26,2012-06-25 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,1.98
12,26,299,26,2012-08-05 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,23.86
13,26,354,26,2013-04-05 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,8.91
14,57,22,57,2009-04-04 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,1.98
15,57,33,57,2009-05-15 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,13.86
16,57,88,57,2010-01-13 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,17.91
17,57,217,57,2011-08-20 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,1.98
18,57,240,57,2011-11-22 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,3.96
19,57,262,57,2012-02-24 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,5.94
20,57,314,57,2012-10-14 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,0.99
21,45,85,45,2010-01-08 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,1.98
22,45,96,45,2010-02-18 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,21.86
23,45,151,45,2010-10-19 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,8.91
24,45,280,45,2012-05-25 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,1.98
25,45,303,45,2012-08-27 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,3.96
26,45,325,45,2012-11-29 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,5.94
27,45,377,45,2013-07-20 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,0.99
28,46,10,46,2009-02-03 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,5.94
29,46,62,46,2009-09-24 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,0.99
30,46,183,46,2011-03-18 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,1.98
31,46,194,46,2011-04-28 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,21.86
32,46,249,46,2011-12-27 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,8.91
33,46,378,46,2013-08-02 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,1.98
34,46,401,46,2013-11-04 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,3.96

## Temporary Tables

Temporary tables adalah sebuah tabel untuk menyimpan hasil sementara selama menjalankan query yang kompleks tanpa mengubah tabel utama dalam database. Temporary tables hanya akan ada selama sesi SQL/Python kita berjalan, berfungsi sebagai workspace sementara untuk transformasi dan agregasi data.  

Temporary tables sangat berguna saat menangani operasi multi-langkah, seperti join beberapa tabel dan melakukan agregasi yang kompleks. Sehingga, temporary tables akan membantu memecah query kompleks menjadi bagian-bagian yang lebih kecil dan mudah dikelola.  

Untuk membuat temporary table, syntax umumnya adalah:  

```sql
CREATE TEMPORARY TABLE temp_table_name AS
```

Untuk pembuatannya di python, tidak menggunakan `pd.read_sql_query()` karena pembuatan temporary table tidak akan menampilkan informasi tabel tersebut, namun menggunakan `conn.execute()`

Kita akan melakukan query top 5 customer yang sebelumnya kita lakukan menggunakan subquery, namun sekarang kita akan buat menggunakan temporary tables:

In [130]:
# code here
query = '''
    CREATE TEMPORARY TABLE top5customer AS
        SELECT CustomerId
        FROM invoices

        GROUP BY CustomerId
        ORDER BY SUM(Total) DESC

        LIMIT 5        
'''

conn.execute(query)

Setelah mendefinisikan temporary table bernama `top5_customer`, kita dapat menggunakannya dalam query kita pada bagian `FROM`:

In [131]:
# code here
query = """
    SELECT *
    FROM top5customer
"""

pd.read_sql_query(query, conn)

   CustomerId
0           6
1          26
2          57
3          45
4          46

Kemudian kita akan lengkapi query tersebut untuk melihat lagu-lagu yang dibeli customer tersebut:

In [132]:
query = """
    SELECT invoices.CustomerId, tracks.Name
    FROM top5customer

    LEFT JOIN invoices ON invoices.CustomerId = top5customer.CustomerId
    LEFT JOIN invoice_items ON invoice_items.InvoiceId = invoices.InvoiceId
    LEFT JOIN tracks ON tracks.TrackId = invoice_items.TrackId
"""

pd.read_sql_query(query, conn)

     CustomerId                               Name
0             6   When You Gonna Learn (Digeridoo)
1             6  Whatever It Is, I Just Can't Stop
2             6                Black Capricorn Day
3             6            Were Do We Go From Here
4             6                        Light Years
..          ...                                ...
185          46                             Poeira
186          46                          Army Ants
187          46                          Gyroscope
188          46                            Release
189          46                            Babylon

[190 rows x 2 columns]

### 🤿 Dive Deeper: Temporary Tables

Sebelumnya, kita juga sudah melakukan pembuatan subquery untuk melihat `invoices` transaksi terbesar (`Total`) untuk masing-masing `CustomerId` sehingga kita dapat melihat `InvoiceId` dan `InvoiceDate`nya.

```sql
SELECT CustomerId, InvoiceId, InvoiceDate, Total
FROM invoices

WHERE (invoices.CustomerId, invoices.Total) IN (
    SELECT CustomerId, MAX(Total) AS MaxTotal
    FROM invoices
    GROUP BY CustomerId
)
```

Gunakan temporary table untuk menghasilkan output yang sama dengan query tersebut!

💡 **Hint**: JOIN dapat menggunakan 2 atau lebih kriteria dengan menggunakan `AND`/`OR`

In [133]:
# code here - temporary table
query = '''
    CREATE TEMPORARY TABLE max_customer AS
        SELECT CustomerId, MAX(Total) AS MaxTotal
        FROM invoices
        GROUP BY CustomerId
'''

conn.execute(query)

In [137]:
# code here - data retrieval
query = """
    SELECT invoices.CustomerId, InvoiceId, InvoiceDate, Total
    FROM max_customer

    LEFT JOIN invoices
    ON invoices.CustomerId = max_customer.CustomerId AND invoices.Total = max_customer.MaxTotal
"""

pd.read_sql_query(query, conn)

    CustomerId  InvoiceId          InvoiceDate  Total
0            1        327  2012-12-07 00:00:00  13.86
1            2         12  2009-02-11 00:00:00  13.86
2            3        110  2010-04-21 00:00:00  13.86
3            4        208  2011-06-29 00:00:00  15.86
4            5        306  2012-09-05 00:00:00  16.86
5            6        404  2013-11-13 00:00:00  25.86
6            7         89  2010-01-18 00:00:00  18.86
7            8        187  2011-03-28 00:00:00  13.86
8            9        285  2012-06-04 00:00:00  13.86
9           10        383  2013-08-12 00:00:00  13.86
10          11         68  2009-10-17 00:00:00  13.86
11          12        166  2010-12-25 00:00:00  13.86
12          13        264  2012-03-03 00:00:00  13.86
13          14        362  2013-05-11 00:00:00  13.86
14          15         47  2009-07-16 00:00:00  13.86
15          16        145  2010-09-23 00:00:00  13.86
16          17        243  2011-12-01 00:00:00  13.86
17          18        341  2013-02-07 00:00:00  13.86
18          19         26  2009-04-14 00:00:00  13.86
19          20        124  2010-06-22 00:00:00  13.86
20          21        222  2011-08-30 00:00:00  13.86
21          22        320  2012-11-06 00:00:00  13.86
22          23          5  2009-01-11 00:00:00  13.86
23          24        103  2010-03-21 00:00:00  15.86
24          25        201  2011-05-29 00:00:00  18.86
25          26        299  2012-08-05 00:00:00  23.86
26          27        397  2013-10-13 00:00:00  13.86
27          28         82  2009-12-18 00:00:00  13.86
28          29        180  2011-02-25 00:00:00  13.86
29          30        278  2012-05-04 00:00:00  13.86
30          31        376  2013-07-12 00:00:00  13.86
31          32         61  2009-09-16 00:00:00  13.86
32          33        159  2010-11-24 00:00:00  13.86
33          34        257  2012-02-01 00:00:00  13.86
34          35        355  2013-04-10 00:00:00  13.86
35          36         40  2009-06-15 00:00:00  13.86
36          37        193  2011-04-23 00:00:00  14.91
37          38        236  2011-10-31 00:00:00  13.86
38          39        334  2013-01-07 00:00:00  13.86
39          40         19  2009-03-14 00:00:00  13.86
40          41        117  2010-05-22 00:00:00  13.86
41          42        215  2011-07-30 00:00:00  13.86
42          43        313  2012-10-06 00:00:00  16.86
43          44        411  2013-12-14 00:00:00  13.86
44          45         96  2010-02-18 00:00:00  21.86
45          46        194  2011-04-28 00:00:00  21.86
46          47        292  2012-07-05 00:00:00  13.86
47          48        390  2013-09-12 00:00:00  13.86
48          49         75  2009-11-17 00:00:00  13.86
49          50        173  2011-01-25 00:00:00  13.86
50          51        271  2012-04-03 00:00:00  13.86
51          52        369  2013-06-11 00:00:00  13.86
52          53         54  2009-08-16 00:00:00  13.86
53          54        152  2010-10-24 00:00:00  13.86
54          55        250  2012-01-01 00:00:00  13.86
55          56        348  2013-03-10 00:00:00  13.86
56          57         88  2010-01-13 00:00:00  17.91
57          58        131  2010-07-23 00:00:00  13.86
58          59        229  2011-09-30 00:00:00  13.86

## Window Function

**Window Functions** adalah salah satu fitur paling powerful di SQL yang memungkinkan kita melakukan perhitungan pada sekumpulan baris sambil tetap menjaga setiap baris individual dalam hasil. Berbeda dengan fungsi aggregate seperti `GROUP BY` yang menggabungkan baris menjadi satu output, window functions mengembalikan nilai untuk setiap row, memberikan konteks sekaligus mempertahankan detail.

Window functions didefinisikan berpasangan dengan statement `OVER()`, di mana kita bisa menentukan:
- `PARTITION BY` untuk membagi data ke dalam kelompok.
- `ORDER BY` untuk menentukan urutan di dalam setiap kelompok.

Struktur umumnya adalah:

```sql
SELECT column_name1, 
       WINDOW_FUNCTION(column_name2) OVER (PARTITION BY column_name3 ORDER BY column_name4) AS new_column
FROM table_name
```

- `WINDOW_FUNCTION`: Window functions yang akan diterapkan
- `column_name1`: Kolom biasa yang akan ditampilkan di output
- `column_name2`: Kolom yang digunakan pada window function
- `column_name3`: Kolom yang digunakan untuk membagi rows ke dalam grup (`PARTITION BY`)
- `column_name4`: Kolom yang digunakan untuk menentukan urutan rows dalam setiap grup (`ORDER BY`)

Pada bagian ini, kita akan mengeksplorasi berbagai jenis window functions.

### Aggregate Window Function

**Aggregate Window Functions** mengubah sifat dari aggregate functions biasa dengan menerapkannya pada setiap row tanpa menggabungkan hasil menjadi satu record, seperti cara kerja `GROUP BY`. Maka, kita bisa menghitung statistik pada tiap kategori namun tetap mempertahankan setiap baris di output.

Untuk Aggregate Window Functions, biasanya kita menggunakan aggregate functions yang sudah dikenal di SQL, tetapi digabungkan dengan klausa `OVER()`. Berikut adalah yang paling umum digunakan:

- `SUM(column)`   : cumulative totals, running sums  
- `AVG(column)`   : moving averages, average per group  
- `COUNT(column)` : jumlah rows dalam sebuah window  
- `MIN(column)`   : nilai terkecil dalam window  
- `MAX(column)`   : nilai terbesar dalam window  

Sebagai contoh, kita mungkin ingin menghitung `Total` untuk setiap `CustomerId` serta menampilkan seluruh informasi kolom-kolom lainnya dari tabel `invoices`:

In [138]:
query = '''
    SELECT *, SUM(Total) AS TotalPerCustomer
    FROM invoices
    GROUP BY CustomerId
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,TotalPerCustomer
0,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,39.62
1,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,37.62
2,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,39.62
3,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96,39.62
4,77,5,2009-12-08 00:00:00,Klanova 9/506,Prague,None,Czech Republic,14700,1.98,40.62
5,46,6,2009-07-11 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,8.91,49.62
6,78,7,2009-12-08 00:00:00,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,1.98,42.62
7,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94,37.62
8,56,9,2009-09-06 00:00:00,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,1.98,37.62
9,25,10,2009-04-09 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,8.91,37.62
10,57,11,2009-09-06 00:00:00,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,1.98,37.62
11,34,12,2009-05-23 00:00:00,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,0.99,37.62
12,35,13,2009-06-05 00:00:00,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,1.98,37.62
13,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91,37.62
14,36,15,2009-06-05 00:00:00,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,1.98,38.62
15,13,16,2009-02-19 00:00:00,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,0.99,37.62
16,14,17,2009-03-04 00:00:00,1 Microsoft Way,Redmond,WA,USA,98052-8300,1.98,39.62
17,112,18,2010-05-12 00:00:00,627 Broadway,New York,NY,USA,10012-2612,1.98,37.62
18,15,19,2009-03-04 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,1.98,38.62
19,113,20,2010-05-12 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,1.98,39.62

Dapat kita lihat bahwa proses tersebut hanya akan menampilkan 1 baris untuk masing-masing customer dan hanya akan menampilkan informasi pertama saja untuk kolom-kolom lainnya. 

Jika kita ingin menampilkan seluruh informasi lainnya setelah melakukan agregasi, kita dapat menggunakan metode window functions seperti berikut:

In [141]:
# code here
query = '''
    SELECT *, SUM(Total) OVER(PARTITION BY CustomerId) AS TotalPerCustomer
    FROM invoices
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,TotalPerCustomer
0,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,39.62
1,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,39.62
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,39.62
3,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,39.62
4,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,39.62
5,327,1,2012-12-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,13.86,39.62
6,382,1,2013-08-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,8.91,39.62
7,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,37.62
8,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,37.62
9,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91,37.62
10,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,37.62
11,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96,37.62
12,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94,37.62
13,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99,37.62
14,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,39.62
15,110,3,2010-04-21 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,13.86,39.62
16,165,3,2010-12-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,8.91,39.62
17,294,3,2012-07-26 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,1.98,39.62
18,317,3,2012-10-28 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.96,39.62
19,339,3,2013-01-30 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,5.94,39.62

📝 Tambahkan `ORDER BY InvoiceDate` pada window function untuk melakukan akumulasi jumlah transaksi tiap waktu!

In [ ]:
# code here - running sum/cummulative total
query = '''
    SELECT *, SUM(Total) OVER(PARTITION BY CustomerId ORDER BY InvoiceDate) AS TotalPerCustomer
    FROM invoices
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,TotalPerCustomer
0,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,3.98
1,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,7.94
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,13.88
3,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,14.87
4,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,16.85
5,327,1,2012-12-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,13.86,30.71
6,382,1,2013-08-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,8.91,39.62
7,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,1.98
8,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,15.84
9,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91,24.75
10,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,26.73
11,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96,30.69
12,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94,36.63
13,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99,37.62
14,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,3.98
15,110,3,2010-04-21 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,13.86,17.84
16,165,3,2010-12-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,8.91,26.75
17,294,3,2012-07-26 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,1.98,28.73
18,317,3,2012-10-28 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.96,32.69
19,339,3,2013-01-30 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,5.94,38.63

### Ranking Window Functions

**Ranking Window Functions** digunakan untuk memberikan urutan atau ranking untuk tiap kategori yang ditentukan. Berbeda dengan aggregate window functions yang meringkas nilai, ranking functions membantu mengidentifikasi posisi relatif dari setiap row berdasarkan aturan sorting dari sebuah kategori.

Berikut adalah beberapa Window Functions yang paling umum digunakan untuk ranking:

- `ROW_NUMBER()` : Memberikan nomor urut unik secara berurutan pada setiap row dalam result set (tidak ada duplikasi, tidak ada celah).  
- `RANK()` : Memberikan ranking dimulai dari 1, tetapi akan meninggalkan gap dalam ranking jika ada nilai yang sama.  
- `DENSE_RANK()` : Mirip dengan `RANK()`, tetapi tidak meninggalkan gap jika ada nilai yang sama.  
- `NTILE(n)` : Membagi rows menjadi `n` kelompok yang kurang lebih sama besar (tiles atau buckets), dan memberikan setiap row ke salah satu kelompok tersebut.  

Kemudian dilanjutkan oleh statement `OVER()`, untuk mengatur:

- `PARTITION BY` untuk menentukan kolom kategori setiap urutan.
- `ORDER BY` untuk menentukan urutan berdasarkan nilai kolom apa.

Sebagai contoh, berikan ranking besarnya `Total` tiap `CustomerId` dari tabel `invoices`!

In [153]:
# code here
query = '''
    SELECT *, RANK() OVER(PARTITION BY CustomerId ORDER BY Total DESC) AS RankingTotalPerCustomer
    FROM invoices
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,RankingTotalPerCustomer
0,327,1,2012-12-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,13.86,1
1,382,1,2013-08-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,8.91,2
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,3
3,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,4
4,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,5
5,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,6
6,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,7
7,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,1
8,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91,2
9,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94,3
10,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96,4
11,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,5
12,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,5
13,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99,7
14,110,3,2010-04-21 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,13.86,1
15,165,3,2010-12-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,8.91,2
16,339,3,2013-01-30 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,5.94,3
17,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,4
18,317,3,2012-10-28 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.96,5
19,294,3,2012-07-26 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,1.98,6

Bandingkan dengan jenis-jenis ranking window functions lainnya!

DENSE RANK = Akan menghilangkan gap di antara ranking yang nilainya sama dengan nilai setelahnya

In [154]:
# code here
query = '''
    SELECT *, DENSE_RANK() OVER(PARTITION BY CustomerId ORDER BY Total DESC) AS RankingTotalPerCustomer
    FROM invoices
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,RankingTotalPerCustomer
0,327,1,2012-12-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,13.86,1
1,382,1,2013-08-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,8.91,2
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,3
3,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,4
4,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,5
5,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,6
6,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,7
7,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,1
8,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91,2
9,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94,3
10,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96,4
11,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,5
12,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,5
13,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99,6
14,110,3,2010-04-21 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,13.86,1
15,165,3,2010-12-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,8.91,2
16,339,3,2013-01-30 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,5.94,3
17,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,4
18,317,3,2012-10-28 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.96,5
19,294,3,2012-07-26 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,1.98,6

In [155]:
# code here
query = '''
    SELECT *, ROW_NUMBER() OVER(PARTITION BY CustomerId ORDER BY Total DESC) AS RankingTotalPerCustomer
    FROM invoices
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,RankingTotalPerCustomer
0,327,1,2012-12-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,13.86,1
1,382,1,2013-08-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,8.91,2
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,3
3,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,4
4,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,5
5,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,6
6,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,7
7,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,1
8,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91,2
9,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94,3
10,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96,4
11,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,5
12,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,6
13,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99,7
14,110,3,2010-04-21 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,13.86,1
15,165,3,2010-12-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,8.91,2
16,339,3,2013-01-30 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,5.94,3
17,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,4
18,317,3,2012-10-28 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.96,5
19,294,3,2012-07-26 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,1.98,6

In [159]:
# code here
query = '''
    SELECT *, NTILE(4) OVER(PARTITION BY CustomerId ORDER BY Total DESC) AS RankingTotalPerCustomer
    FROM invoices
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,RankingTotalPerCustomer
0,327,1,2012-12-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,13.86,1
1,382,1,2013-08-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,8.91,1
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,2
3,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,2
4,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,3
5,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,3
6,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,4
7,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,1
8,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91,1
9,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94,2
10,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96,2
11,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,3
12,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,3
13,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99,4
14,110,3,2010-04-21 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,13.86,1
15,165,3,2010-12-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,8.91,1
16,339,3,2013-01-30 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,5.94,2
17,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,2
18,317,3,2012-10-28 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.96,3
19,294,3,2012-07-26 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,1.98,3

### Value Window Functions

**Value Window Functions** memungkinkan KITA untuk mereferensikan nilai dari baris lain dalam sebuah window data yang sudah didefinisikan. Berbeda dengan agregasi atau ranking, fungsi ini melihat nilai dari sekitar baris tersebut untuk mengambil informasi. Sehingga, fungsi ini sangat berguna dalam analisis time-series, pelacakan transaksi customer dari waktu-ke-waktu, dan perbandingan row-to-row di mana konteks dari baris yang berdekatan menjadi penting.

Contoh paling umum dari **Value Window Functions** adalah:

- `LAG(column, offset)` : mengembalikan nilai dari baris sebelumnya dalam partition yang sama.
- `LEAD(column, offset)` : mengembalikan nilai dari baris setelahnya dalam partition yang sama.
- `FIRST_VALUE(column)` : mengembalikan nilai pertama dalam ordered window.
- `LAST_VALUE(column)` : mengembalikan nilai terakhir dalam ordered window.

Misalnya kita ingin membandingkan setiap transaksi customer dengan transaksi sebelumnya:

In [163]:
# code here
query = '''
    SELECT *, LAG(Total, 1) OVER(PARTITION BY CustomerId ORDER BY InvoiceDate) AS PreviousTransaction
    FROM invoices
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,PreviousTransaction
0,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,NaN
1,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,3.98
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,3.96
3,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,5.94
4,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,0.99
5,327,1,2012-12-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,13.86,1.98
6,382,1,2013-08-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,8.91,13.86
7,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,NaN
8,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,1.98
9,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91,13.86
10,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,8.91
11,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96,1.98
12,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94,3.96
13,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99,5.94
14,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,NaN
15,110,3,2010-04-21 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,13.86,3.98
16,165,3,2010-12-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,8.91,13.86
17,294,3,2012-07-26 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,1.98,8.91
18,317,3,2012-10-28 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.96,1.98
19,339,3,2013-01-30 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,5.94,3.96

Bandingkan dengan jenis-jenis ranking window functions lainnya!

In [170]:
# code here
query = '''
    SELECT *, LEAD(Total, 2) OVER(PARTITION BY CustomerId ORDER BY InvoiceDate) AS PreviousTransaction
    FROM invoices
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,PreviousTransaction
0,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,5.94
1,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,0.99
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,1.98
3,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,13.86
4,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,8.91
5,327,1,2012-12-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,13.86,NaN
6,382,1,2013-08-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,8.91,NaN
7,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,8.91
8,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,1.98
9,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91,3.96
10,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,5.94
11,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96,0.99
12,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94,NaN
13,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99,NaN
14,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,8.91
15,110,3,2010-04-21 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,13.86,1.98
16,165,3,2010-12-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,8.91,3.96
17,294,3,2012-07-26 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,1.98,5.94
18,317,3,2012-10-28 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.96,0.99
19,339,3,2013-01-30 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,5.94,NaN

In [165]:
# code here
query = '''
    SELECT *, FIRST_VALUE(Total) OVER(PARTITION BY CustomerId ORDER BY InvoiceDate) AS PreviousTransaction
    FROM invoices
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,PreviousTransaction
0,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,3.98
1,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,3.98
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,3.98
3,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,3.98
4,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,3.98
5,327,1,2012-12-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,13.86,3.98
6,382,1,2013-08-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,8.91,3.98
7,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,1.98
8,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,1.98
9,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91,1.98
10,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,1.98
11,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96,1.98
12,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94,1.98
13,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99,1.98
14,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,3.98
15,110,3,2010-04-21 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,13.86,3.98
16,165,3,2010-12-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,8.91,3.98
17,294,3,2012-07-26 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,1.98,3.98
18,317,3,2012-10-28 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.96,3.98
19,339,3,2013-01-30 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,5.94,3.98

In [169]:
# code here
query = '''
    SELECT *, LAST_VALUE(Total) OVER(PARTITION BY CustomerId) AS PreviousTransaction
    FROM invoices
'''

pd.read_sql_query(query, conn).head(20)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,PreviousTransaction
0,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,8.91
1,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,8.91
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,8.91
3,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,8.91
4,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,8.91
5,327,1,2012-12-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,13.86,8.91
6,382,1,2013-08-07 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,8.91,8.91
7,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,0.99
8,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86,0.99
9,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91,0.99
10,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98,0.99
11,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96,0.99
12,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94,0.99
13,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99,0.99
14,99,3,2010-03-11 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.98,0.99
15,110,3,2010-04-21 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,13.86,0.99
16,165,3,2010-12-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,8.91,0.99
17,294,3,2012-07-26 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,1.98,0.99
18,317,3,2012-10-28 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,3.96,0.99
19,339,3,2013-01-30 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,5.94,0.99

# Under and Over Fetching

Di antara semua tools yang telah kita pelajari untuk menganalisis data, sekarang saatnya kita merenungkan yang mana yang lebih cocok untuk Anda. Untuk meninjau, mari kita ingat kembali apa yang telah kita pelajari:

- Reading flat files (CSV file)
- Data cleansing and wrangling
- Exploratory data analysis tools
- Visual exploratory tools

Kira-kira SQL masuk ke bagian apa? Untuk menjawab hal tersebut, Anda perlu memahami arsitektur client-server.

![](assets/clientserver.png)

Ketika Anda bekerja dengan SQL, kemungkinan besar Anda memiliki database relasional yang disimpan terpusat pada _server_ dan dapat diakses oleh _client_. Pada dasarnya _server_ adalah komputer penyedia data, dan _client_ adalah komputer pengambil data (komputer Anda).

Saat Anda melakukan query, sebenarnya Anda sedang menjalankan perintah untuk mengunduh data ke komputer Anda (_local computer_). Proses pengunduhan ini membutuhkan sumber daya, sehingga pengunduhan perlu dilakukan secara efektif untuk meminimalkan biaya.

- **Over** fetching adalah kondisi ketika kita menarik data dari database **lebih dari** yang dibutuhkan, sehingga membutuhkan biaya dan waktu yang lebih.

- **Under** fetching adalah kondisi sebaliknya, dimana data yang ditarik **kurang dari** yang dibutuhkan, sehingga proses analisis tidak dapat dilakukan secara lengkap.