# Business Understanding

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df = pd.read_csv('marine_engine_data.csv')

In [27]:
df

,timestamp,engine_id,engine_temp,oil_pressure,fuel_consumption,vibration_level,rpm,engine_load,coolant_temp,exhaust_temp,running_period,fuel_consumption_per_hour,maintenance_status,failure_mode,engine_type,fuel_type,manufacturer
0,2023-01-01,ENG_001,79.816406,7.049409,1000.000000,4.366612,1770.214578,42.472407,78.323108,450.0,49.741791,100.0,Critical,Oil Leakage,4-stroke High-Speed,Diesel,MAN B&W
1,2023-01-08,ENG_001,98.982068,8.000000,6308.623817,3.732792,1677.238238,77.042858,100.000000,450.0,94.351515,100.0,Requires Maintenance,Oil Leakage,2-stroke Low-Speed,Diesel,Mitsubishi
2,2023-01-15,ENG_001,83.918153,8.000000,6444.402260,4.061372,1487.472085,63.919637,78.178337,450.0,120.095804,100.0,Normal,No Failure,2-stroke Medium-Speed,Diesel,Caterpillar
3,2023-01-22,ENG_001,81.887081,7.601603,4439.946613,3.999554,1548.624692,55.919509,82.896344,450.0,122.321555,100.0,Requires Maintenance,Mechanical Wear,2-stroke Medium-Speed,Diesel,MAN B&W
4,2023-01-29,ENG_001,78.550429,6.233033,3146.234038,4.520559,1441.151499,29.361118,80.791150,450.0,111.978460,100.0,Normal,No Failure,4-stroke High-Speed,Diesel,Wärtsilä
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5195,2024-11-24,ENG_050,92.745290,7.956103,7680.773408,3.961213,1357.996911,67.879882,93.227957,450.0,109.063800,100.0,Critical,Overheating,2-stroke Medium-Speed,HFO,Caterpillar
5196,2024-12-01,ENG_050,89.462079,8.000000,1265.703232,3.895100,1525.999645,64.312763,85.860150,450.0,41.032231,100.0,Normal,Oil Leakage,4-stroke High-Speed,Diesel,MAN B&W
5197,2024-12-08,ENG_050,79.057910,6.413932,4052.497442,3.272452,1287.392745,23.827673,82.431163,450.0,151.801942,100.0,Normal,Oil Leakage,4-stroke Medium-Speed,HFO,MAN B&W
5198,2024-12-15,ENG_050,79.379851,7.437593,1000.000000,3.450956,1584.249476,43.233388,75.937160,450.0,16.715902,100.0,Critical,Mechanical Wear,2-stroke Medium-Speed,HFO,Rolls-Royce
5199,2024-12-22,ENG_050,78.091169,7.137819,3589.190365,3.824081,1669.367989,36.965927,72.909996,450.0,110.235183,100.0,Requires Maintenance,Mechanical Wear,2-stroke Medium-Speed,Diesel,Rolls-Royce

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   timestamp                  5200 non-null   object
 1   engine_id                  5200 non-null   object
 2   engine_temp                5200 non-null   float64
 3   oil_pressure               5200 non-null   float64
 4   fuel_consumption           5200 non-null   float64
 5   vibration_level            5200 non-null   float64
 6   rpm                        5200 non-null   float64
 7   engine_load                5200 non-null   float64
 8   coolant_temp               5200 non-null   float64
 9   exhaust_temp               5200 non-null   float64
 10  running_period             5200 non-null   float64
 11  fuel_consumption_per_hour  5200 non-null   float64
 12  maintenance_status         5200 non-null   object
 13  failure_mode               5200 non-null   object
 14  engine_type                5200 non-null   object
 15  fuel_type                  5200 non-null   object
 16  manufacturer               5200 non-null   object
dtypes: float64(10), object(7)
memory usage: 690.8+ KB

In [23]:
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['maintenance_status'] = df['maintenance_status'].astype('category')
df['failure_mode'] = df['failure_mode'].astype('category')
df['fuel_type'] = df['fuel_type'].astype('category')
df['manufacturer'] = df['manufacturer'].astype('category')
df['engine_type'] = df['engine_type'].astype('category')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   timestamp                  5200 non-null   datetime64[ns]
 1   engine_id                  5200 non-null   object
 2   engine_temp                5200 non-null   float64
 3   oil_pressure               5200 non-null   float64
 4   fuel_consumption           5200 non-null   float64
 5   vibration_level            5200 non-null   float64
 6   rpm                        5200 non-null   float64
 7   engine_load                5200 non-null   float64
 8   coolant_temp               5200 non-null   float64
 9   exhaust_temp               5200 non-null   float64
 10  running_period             5200 non-null   float64
 11  fuel_consumption_per_hour  5200 non-null   float64
 12  maintenance_status         5200 non-null   category
 13  failure_mode               5200 non-null   category
 14  engine_type                5200 non-null   category
 15  fuel_type                  5200 non-null   category
 16  manufacturer               5200 non-null   category
dtypes: category(5), datetime64[ns](1), float64(10), object(1)
memory usage: 513.9+ KB

In [25]:
df.describe()

,timestamp,engine_temp,oil_pressure,fuel_consumption,vibration_level,rpm,engine_load,coolant_temp,exhaust_temp,running_period,fuel_consumption_per_hour
count,5200,5200.000000,5200.000000,5200.000000,5200.000000,5200.000000,5200.000000,5200.000000,5200.000000,5200.000000,5200.000000
mean,2023-12-27 12:00:00,85.067979,7.281496,3937.674530,3.746574,1496.909900,49.794979,85.000245,449.829456,84.045362,116.270048
min,2023-01-01 00:00:00,60.524875,5.000000,1000.000000,2.500000,732.668890,20.000698,70.000000,426.124325,0.026501,100.000000
25%,2023-06-30 06:00:00,79.895619,6.723802,1880.183832,3.500402,1362.119419,34.631768,79.567776,450.000000,41.128329,100.000000
50%,2023-12-27 12:00:00,85.043649,7.484437,3458.765539,3.744904,1496.020797,49.965640,84.999981,450.000000,84.034658,100.000000
75%,2024-06-24 18:00:00,90.284900,8.000000,5579.230554,3.994230,1635.905091,64.850333,90.397305,450.000000,127.258907,100.000000
max,2024-12-22 00:00:00,107.357690,8.000000,12672.543097,5.000000,2205.811038,79.983060,100.000000,450.000000,167.987371,800.000000
std,NaN,7.244281,0.750153,2439.427599,0.366415,202.952635,17.366150,7.475177,1.302990,48.932473,82.219935

In [26]:
df.describe(include='category')

,maintenance_status,failure_mode,engine_type,fuel_type,manufacturer
count,5200,5200,5200,5200,5200
unique,3,4,4,2,6
top,Requires Maintenance,Oil Leakage,4-stroke High-Speed,Diesel,MAN B&W
freq,1756,1605,1548,3084,1562

In [29]:
df.describe(include='object')

       engine_id
count       5200
unique        50
top      ENG_001
freq         104

In [40]:
df = df.drop(columns=['timestamp', 'engine_id'])

In [45]:
df['is_target'] = df['maintenance_status'].apply(lambda x: 1 if x in ['Requires Maintenance','Critical'] else 0)

In [48]:
df[['is_target','maintenance_status']].value_counts()

is_target  maintenance_status
1          Requires Maintenance    1756
           Critical                1740
0          Normal                  1704
Name: count, dtype: int64

In [49]:
df.count()

engine_temp                  5200
oil_pressure                 5200
fuel_consumption             5200
vibration_level              5200
rpm                          5200
engine_load                  5200
coolant_temp                 5200
exhaust_temp                 5200
running_period               5200
fuel_consumption_per_hour    5200
maintenance_status           5200
failure_mode                 5200
engine_type                  5200
fuel_type                    5200
manufacturer                 5200
is_target                    5200
dtype: int64