# Quiz: Python for Exploratory Data Analysts

Selamat Anda sudah menyelesaikan materi **Python for Exploratory Data Analysts**! Kami akan melakukan penilaian berupa kuis untuk menguji materi yang sudah dipelajari. Pengerjaan Kuis diharapkan dapat dilakukan di dalam kelas, silakan hubungi tim pengajar kami apabila Anda melewatkan kesempatan untuk mengambilnya di kelas.

In [1]:
import pandas as pd

## Data Pre-Processing

Pada kuis ini kita akan menggunakan **Companies dataset**. Anda dapat menggunakan data dalam ekstensi csv file yang tersimpan dalam `companies.csv` file. Companies dataset merupakan sebagian contoh dari data CRM (customer relationship management) yang mengandung beberapa variable sebagai berikut :

- `ID` : identifier unique dari nama cutomer
- `Customer Name` : nama customer (nama company)
- `Consulting Sales` : harga untuk service konsultasi
- `Software Sales` : harga untuk service software
- `Forecasted Growth` : presentase pertumbuhan company dalam kurun waktu tertentu
- `Returns` : dana yang kembali (Returns) dalam kurun waktu tertentu
- `Month` : bulan berdirinya company
- `Day` : tanggal berdirinya company
- `Year` : tahun berdirinya company
- `Location` : lokasi company
- `Account` : jenis customer company

In [2]:
clients = pd.read_csv("data_input/companies.csv", index_col=0)
clients.head()

,Customer Name,Consulting Sales,Software Sales,Forecasted Growth,Returns,Month,Day,Year,Location,Account
ID,,,,,,,,,,
30940,New Media Group,IDR7125000,IDR5500000,30.00%,"IDR1,500,000",1,10,2017,Jakarta,Enterprise
82391,Li and Partners,IDR420000,IDR820000,10.00%,"IDR400,000",6,15,2016,Jakarta,Startup
18374,PT. Kreasi Metrik Solusi,0,IDR550403,25.00%,0,3,29,2012,Surabaya,Enterprise
57531,PT. Algoritma Data Indonesia,IDR850000,IDR395500,4.00%,0,7,17,2017,Jakarta,Startup
19002,Palembang Konsultansi,IDR2115000,0,-15.00%,0,2,24,2018,Bandung,Startup

Apabila Anda perhatikan, dataset `clients` memiliki format yang sedikit berbeda dengan dataset yang sudah kita gunakan pada materi. Kolom `Returns` memiliki karakter koma (`,`) sebagai pemisah satuan ribuan dan simbol mata uang (`IDR`) pada valuenya.

Mari kita tinjau lebih jauh tipe data pada variabel `clients`:

In [3]:
clients.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 30940 to 31142
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer Name      6 non-null      object
 1   Consulting Sales   6 non-null      object
 2   Software Sales     6 non-null      object
 3   Forecasted Growth  6 non-null      object
 4   Returns            6 non-null      object
 5   Month              6 non-null      int64
 6   Day                6 non-null      int64
 7   Year               6 non-null      int64
 8   Location           6 non-null      object
 9   Account            6 non-null      object
dtypes: int64(3), object(7)
memory usage: 528.0+ bytes

In [4]:
clients.dtypes

Customer Name        object
Consulting Sales     object
Software Sales       object
Forecasted Growth    object
Returns              object
Month                 int64
Day                   int64
Year                  int64
Location             object
Account              object
dtype: object

In [5]:
clients.describe(include='all')

,Customer Name,Consulting Sales,Software Sales,Forecasted Growth,Returns,Month,Day,Year,Location,Account
count,6,6,6,6,6,6.000000,6.000000,6.000000,6,6
unique,6,6,6,6,3,NaN,NaN,NaN,3,2
top,New Media Group,IDR7125000,IDR5500000,30.00%,0,NaN,NaN,NaN,Jakarta,Enterprise
freq,1,1,1,1,4,NaN,NaN,NaN,4,3
mean,NaN,NaN,NaN,NaN,NaN,3.333333,19.000000,2016.500000,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,2.581989,6.723095,2.428992,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,1.000000,10.000000,2012.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,1.250000,15.500000,2016.250000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,2.500000,18.000000,2017.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,5.250000,22.750000,2017.750000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,7.000000,29.000000,2019.000000,NaN,NaN

Pada hasil tersebut di atas, dapat diketahui bahwa beberapa variable tidak tersimpan pada format tipe data yang tepat. Dapatkah Anda mengubah tipe data beberapa variable tersebut menjadi bentuk tipe data yang tepat?

In [6]:
## Your Code Below:
clients['Account'] = clients['Account'].astype('category')
clients['Location'] = clients['Location'].astype('category')

Apabila Anda sudah mencoba mengubah tipe data menggunakan method `.astype()`, maka Anda akan mendapatkan pesan error ketika mengubah tipe data pada kolom `Consulting Sales` dan `Software Sales`. Hal ini dikarenakan komputasi dan pengubahan tipe data numerik pada python tidak dapat dilakukan ketika terdapat karakter tertentu dalam data. Oleh karena itu, perlu dilakukan penghapusan karakter `IDR` yang terdapat pada kedua kolom tersebut. Penghapusan karakter dapat menggunakan built-in method pada `pandas` yaitu `str.replace()`. Berikut adalah contoh penggunaannya:

In [7]:
clients['Consulting Sales'].str.replace('IDR','')

ID
30940    7125000
82391     420000
18374          0
57531     850000
19002    2115000
31142     960000
Name: Consulting Sales, dtype: object

Untuk mengaplikasikannya pada beberapa kolom dapat menggunakan method `apply` dengan `lambda` sebagai berikut :

In [8]:
clients[['Consulting Sales','Software Sales','Returns']] =\
clients[['Consulting Sales','Software Sales','Returns']].apply(lambda x: x.str.replace('IDR',''))

In [9]:
clients.head()

,Customer Name,Consulting Sales,Software Sales,Forecasted Growth,Returns,Month,Day,Year,Location,Account
ID,,,,,,,,,,
30940,New Media Group,7125000,5500000,30.00%,"1,500,000",1,10,2017,Jakarta,Enterprise
82391,Li and Partners,420000,820000,10.00%,"400,000",6,15,2016,Jakarta,Startup
18374,PT. Kreasi Metrik Solusi,0,550403,25.00%,0,3,29,2012,Surabaya,Enterprise
57531,PT. Algoritma Data Indonesia,850000,395500,4.00%,0,7,17,2017,Jakarta,Startup
19002,Palembang Konsultansi,2115000,0,-15.00%,0,2,24,2018,Bandung,Startup

Lengkapi kode program di bawah ini untuk menghilangkan tanda koma (`,`) pada kolom `Returns`! \
Contoh : `clients['Consulting Sales'] = clients['Consulting Sales'].str.replace('IDR','')` digunakan untuk menghilangkan `IDR` pada kolom `Consulting Sales`

In [10]:
## Fill in the blank (___)

clients['Returns'] = clients['Returns'].str.replace(',','')

In [11]:
clients['Returns'] = clients['Returns'].astype(int)

In [12]:
clients['Consulting Sales'] = clients['Consulting Sales'].astype(int)
clients['Software Sales'] = clients['Software Sales'].astype(int)

In [13]:
clients.dtypes

Customer Name          object
Consulting Sales        int32
Software Sales          int32
Forecasted Growth      object
Returns                 int32
Month                   int64
Day                     int64
Year                    int64
Location             category
Account              category
dtype: object

---

## Data Analisis

Sebagai seorang Data Analyst, Anda diminta untuk mendapatkan total penjualan secara keseluruhan dengan mengakumulasikan nilai Consulting Sales dan Software Sales dari setiap perusahaan. Buatlah kolom baru bernama `Total Sales` yang menyimpan total dari kedua nilai tersebut. 

---
1. Berapa total (`sum`) keseluruhan dari `Total Sales`? Tips: Gunakan method `.sum()` pada kolom untuk mengakumulasi nilai totalnya!
    - [ ] 11,470,000
    - [ ] 19,238,903
    - [ ]  7,768,903
---

In [14]:
## Your Code Below:
clients['Total Sales'] = clients['Consulting Sales'] + clients['Software Sales']
clients['Total Sales'].sum()

19238903

Berdasarkan total penjualan yang diperoleh setiap tahunnya, Anda sedang berokus untuk menganalisa penjualan dari masing-masing client pada tahun 2017 silam. Oleh karena itu, saat ini Anda akan fokus pada perusahaan yang menjadi client pada tahun 2017. Lakukanlah subseting untuk mendapatkan informasi data penjualan yang terjadi pada tahun 2017. Gunakanlah metode subseting yang sudah Anda pelajari.

---
2. Perusahaan manakah yang mendapatkan `Total Sales` terbesar di tahun 2017? 
    
    - [ ] New Media Group
    - [ ] PT. Algoritma Data Indonesia
    - [ ] Palembang Konsultansi
---

In [15]:
## Your Code Below:
clients[clients['Year']==2017].groupby('Customer Name')['Total Sales'].sum().sort_values(ascending=False)

Customer Name
New Media Group                 12625000
PT. Algoritma Data Indonesia     1245500
Name: Total Sales, dtype: int32

Setelah itu, kita akan kembali fokus menggunakan seluruh data yang ada. Menggunakan seluruh data yang ada, ternyata perusahaan ingin melakukan *campaign* terhadap perusahaan yang memiliki nilai penjualan lebih dari 1,500,000 IDR. Silahkan gunakan subsetting kembali untuk mengetahui perusahaan yang memiliki penjualan lebih dari 1,500,000 IDR. Ternyata ada dua perusahaan yang nilai penjualannya melebihi 1,500,000 IDR pada data tersebut.

---
3.  Perusahaan mana saja yang memiliki penjualan lebih dari 1,500,000 IDR?

    - [ ] Palembang Konsultansi & PT. Surya Citra Manajemen
    - [ ] PT. Surya Citra Manajemen & New Media Group
    - [ ] Palembang Konsultansi & New Media Group
---

In [16]:
## Your Code Below:
customer_name = pd.DataFrame(clients.groupby('Customer Name')['Total Sales'].sum()).sort_values(by='Total Sales', ascending=False)
customer_name[customer_name['Total Sales'] > 1500000]

                       Total Sales
Customer Name
New Media Group           12625000
Palembang Konsultansi      2115000

Terakhir, Anda diminta untuk melakukan analisa pada client yang berlokasi di Jakarta dan termasuk kedalam akun Enterprise. Untuk melakukan subsetting, silahkan lengkapi syntax berikut dan jawablah pertanyaan dibawah ini.

```
clients[________ _ ________]
```

---
4. Berdasarkan syntax yang Anda lengkapi diatas, manakah pilihan syntax dibawah ini yang tepat untuk melengkapi?

    - [ ] (clients.Location == "Jakarta") | (clients.Account == "Enterprise")
    - [ ] clients.Location == "Jakarta" & clients.Account == "Enterprise"
    - [ ] (clients.Location == "Jakarta") & (clients.Account == "Enterprise")
    - [ ] clients.Location == "Jakarta" | clients.Account == "Enterprise"
---

In [17]:
## Your Code Below:
clients[(clients['Location'] == 'Jakarta') & (clients['Account'] =='Enterprise')]

,Customer Name,Consulting Sales,Software Sales,Forecasted Growth,Returns,Month,Day,Year,Location,Account,Total Sales
ID,,,,,,,,,,,
30940,New Media Group,7125000,5500000,30.00%,1500000,1,10,2017,Jakarta,Enterprise,12625000
31142,PT. Surya Citra Manajemen,960000,503000,19.00%,0,1,19,2019,Jakarta,Enterprise,1463000

# Dataset Bukalapak

## Data Preparation

Pada kuis ini kita akan menggunakan **e-commerce product dataset**. Anda dapat menggunakan data `online_bl.csv` yang tersimpan dalam folder `data_input`. 

Data berisi informasi produk yang dijual pada website e-commerce bukalapak.com. Data tersebut memiliki beberapa variable antara lain :

- `item_link` : link website produk dalam list  
- `title` : nama produk yang dijual
- `price_original` : harga produk
- `price_discount` : harga discount produk
- `sub_category` : sub-category produk
- `time_update` : waktu unggah informasi produk pada website
- `scale` : skala satuan product

Silahkan import data `online_bl.csv` dari folder `data_input` dan simpan kedalam variabel `online_bl`. Gunakan parameter `parse_dates=[__]` pada method `read_csv()` untuk mengubah tipe data pada kolom `time_update`.

In [18]:
## Import Library & Read Data
import pandas as pd

online_bl = pd.read_csv("data_input/online_bl.csv", parse_dates = ['time_update'])

Anda akan melakukan eksplorasi data `online_bl` untuk memastikan bahwa data tersebut siap untuk dianalisis. Hal yang pertama akan Anda lakukan adalah melakukan pengecekan tipe data.

In [19]:
# your code here
online_bl.dtypes

item_link                 object
title                     object
price_original           float64
price_discount           float64
sub_category              object
time_update       datetime64[ns]
scale                     object
dtype: object

Terdapat kolom yang perlu disesuaikan tipe datanya yaitu kolom `sub_category`. Silahkan lakukan pengubahan tipe data pada kolom tersebut kedalam tipe data yang sesuai.

In [21]:
# your code here
online_bl['sub_category'] =online_bl['sub_category'].astype('category')

## Analisis

Data `online_bl` menyimpan data beragam barang yang dijual pada suatu e-commerce. Anda diminta untuk melakukan analisis terhadap data untuk menjawab beberapa pertanyaan yang ada.

### Jenis Barang

Anda ingin mencari tahu jenis barang apa saja yang dijual dan jenis barang apakah yang paling banyak dijual pada e-commerce tersebut. Menggunakan informasi dari kolom `sub_category`, silahkan jawab pertanyaan di bawah ini.

5. Berapa banyak jenis barang (`sub_category`) unik yang ada dalam kumpulan data `online_bl`? Apakah kita memiliki lebih banyak produk "detergent" atau "sugar" pada data tersebut?

    - [ ] 2, dimana "detergent" lebih banyak dari pada "Sugar"
    - [ ] 2, dimana "detergent" dan "sugar" memiliki jumlah produk sama banyak
    - [ ] 3, dimana "sugar" lebih banyak dari pada detergent
    - [ ] tidak ada opsi yang benar

- Opsi jawaban Bahasa Inggris:

    - [ ] 2, with more "detergent" than "sugar"
    - [ ] 2, with "detergent" and "sugar" having equal listings
    - [ ] 3, with more "sugar" than detergent
    - [ ] None of above is correct

In [22]:
# your code here
online_bl.head()

,item_link,title,price_original,price_discount,sub_category,time_update,scale
0,https://www.bukalapak.com/p/kesehatan-2359/pro...,Rinso Molto Deterjen Bubuk 1.8 kg,30000.0,NaN,detergent,2018-10-20 01:32:00,1.8 kg
1,https://www.bukalapak.com/p/rumah-tangga/home-...,Terlaris - DETERGENT RINSO ANTI NODA 1.8 KG 1 ...,49000.0,NaN,detergent,2018-09-20 01:02:00,1.8 kg
2,https://www.bukalapak.com/p/rumah-tangga/home-...,Good Rinso Molto Purple 1.8 Kg,50000.0,NaN,detergent,2018-10-13 10:46:00,1.8 kg
3,https://www.bukalapak.com/p/rumah-tangga/home-...,Order Rinso Molto Purple 1.8 Kg,49000.0,NaN,detergent,2018-09-24 15:17:00,1.8 kg
4,https://www.bukalapak.com/p/rumah-tangga/home-...,Promonya Rinso Molto Purple 1.8 Kg,49000.0,NaN,detergent,2018-09-27 11:16:00,1.8 kg

In [26]:
online_bl.describe(include='all')

,item_link,title,price_original,price_discount,sub_category,time_update,scale
count,744,744,728.000000,17.000000,744,744,744
unique,689,659,NaN,NaN,3,NaN,4
top,https://www.bukalapak.com/p/rumah-tangga/perle...,Rinso anti noda 1.8 kg,NaN,NaN,rice,NaN,1 kg
freq,3,7,NaN,NaN,425,NaN,364
mean,NaN,NaN,65660.027473,50352.941176,NaN,2018-09-28 04:50:39.919354880,NaN
min,NaN,NaN,700.000000,11900.000000,NaN,2018-01-08 17:04:00,NaN
25%,NaN,NaN,28000.000000,15200.000000,NaN,2018-09-21 09:11:30,NaN
50%,NaN,NaN,50000.000000,38500.000000,NaN,2018-10-10 01:37:00,NaN
75%,NaN,NaN,75000.000000,63700.000000,NaN,2018-10-18 14:13:00,NaN
max,NaN,NaN,457400.000000,160200.000000,NaN,2018-10-22 14:18:00,NaN
std,NaN,NaN,65187.800932,46393.064105,NaN,NaN,NaN

In [25]:
online_bl.groupby('sub_category')['item_link'].count().sort_values(ascending=False)

sub_category
rice         425
sugar        213
detergent    106
Name: item_link, dtype: int64

In [61]:
online_bl.groupby('sub_category')['title'].nunique().sort_values(ascending=False)

sub_category
rice         405
sugar        204
detergent     52
Name: title, dtype: int64

### Skala Barang

Berdasarkan beberapa jenis barang yang dijual diatas, setiap barang dijual dengan beberapa ukuran berdasarkan beratnya, termasuk deterjen. Deterjen yang ada di pasaran memiliki beberapa pilihan ukuran (1kg, 1.8kg, dsb). 

6. Deterjen dengan ukuran berapakah yang paling banyak dijual di situs Bukalapak?

    - [ ] 1 kg
    - [ ] 1.8 kg
    - [ ] 5 kg
    - [ ] 800 gr

In [30]:
online_bl[online_bl['sub_category']=='detergent']['scale'].value_counts()

scale
1.8 kg    88
800 gr    18
Name: count, dtype: int64

In [29]:
# your code here
online_bl[online_bl['sub_category']=='detergent'].groupby('scale')['item_link'].count().sort_values(ascending=False)

scale
1.8 kg    88
800 gr    18
Name: item_link, dtype: int64

Anda sedang membutuhkan produk deterjen. Berdasarkan informasi ukuran deterjen serta harga yang dipasarkan, Anda tertarik untuk membeli deterjen dengan ukuran 1,8 kg dan 800 gram. Namun, Anda ingin mengetahui pada bulan apa deterjen dengan ukuran tersebut dijual dengan rata-rata harga terendah.  

7. Di bulan apakah produk deterjen dengan ukuran 1,8 kg dan 800 gram berada di rata-rata harga (`price_original`) terendah? Apakah keduanya berada di bulan yang sama?

    - [ ] Detergen 1.8 kg dan 800 gr memiliki harga terendah di bulan Agustus
    - [ ] Detergen 1.8 kg dan 800 gr memiliki harga terendah di bulan Oktober
    - [ ] Detergen 1.8 kg: terendah di Agustus, Detergen 800 gr: terendah di Oktober
    - [ ] Detergen 1.8 kg: terendah di August, Detergen 800 gr: terendah di July 
    
- Opsi Jawaban Bahasa Inggris:

    - [ ] Both 1.8 kg and 800 gr detergents lowest price were in August
    - [ ] Both 1.8 kg and 800 gr detergents lowest price were in October
    - [ ] 1.8 kg detergents: Lowest in August, 800 gr: Lowest in October
    - [ ] 1.8 kg detergents: Lowest in August, 800 gr: Lowest in July

In [31]:
# run this code to extract the month

online_bl['month'] = online_bl['time_update'].dt.month_name()

In [32]:
online_bl.head()

,item_link,title,price_original,price_discount,sub_category,time_update,scale,month
0,https://www.bukalapak.com/p/kesehatan-2359/pro...,Rinso Molto Deterjen Bubuk 1.8 kg,30000.0,NaN,detergent,2018-10-20 01:32:00,1.8 kg,October
1,https://www.bukalapak.com/p/rumah-tangga/home-...,Terlaris - DETERGENT RINSO ANTI NODA 1.8 KG 1 ...,49000.0,NaN,detergent,2018-09-20 01:02:00,1.8 kg,September
2,https://www.bukalapak.com/p/rumah-tangga/home-...,Good Rinso Molto Purple 1.8 Kg,50000.0,NaN,detergent,2018-10-13 10:46:00,1.8 kg,October
3,https://www.bukalapak.com/p/rumah-tangga/home-...,Order Rinso Molto Purple 1.8 Kg,49000.0,NaN,detergent,2018-09-24 15:17:00,1.8 kg,September
4,https://www.bukalapak.com/p/rumah-tangga/home-...,Promonya Rinso Molto Purple 1.8 Kg,49000.0,NaN,detergent,2018-09-27 11:16:00,1.8 kg,September

In [39]:
# your code here
pd.DataFrame(online_bl[(online_bl['sub_category']=='detergent')&(online_bl['scale'].isin(['1.8 kg','800 gr']))].groupby(['scale','month'])['price_original'].mean().sort_values().reset_index())

    scale      month  price_original
0  800 gr     August    20000.000000
1  800 gr    October    21945.454545
2  800 gr       July    30000.000000
3  1.8 kg     August    31000.000000
4  800 gr  September    33475.000000
5  1.8 kg       July    40000.000000
6  1.8 kg    October    41191.836735
7  1.8 kg  September    42750.000000

---

8. Bagaimana cara mengekstrak hari dalam seminggu (sebagai angka, di mana Senin adalah 0 dan Minggu adalah 6) dari kolom tanggal dalam sebuah DataFrame df?

    - [ ] df['tanggal'].dt.weekday
    - [ ] df['tanggal'].weekday    
    - [ ] df['tanggal'].dt.day_of_week()
    - [ ] df['tanggal'].dt.weekofday()

In [59]:
online_bl['day'] = online_bl['time_update'].dt.day_of_week
online_bl['day_name'] = online_bl['time_update'].dt.day_name()
online_bl[['time_update','day','day_name']].head()
online_bl[['day','day_name']].drop_duplicates().sort_values('day')

    day   day_name
3     0     Monday
41    1    Tuesday
25    2  Wednesday
1     3   Thursday
7     4     Friday
0     5   Saturday
8     6     Sunday